### PR TITLE
Fix AWS auth credentials chain and upgrade minio-go

### LINKED ISSUE #2888: 2.2.2 regression: S3 storage does not work with AWS IRSA authentication anymore
**Describe the bug**
After upgrading Tempo from `2.2.1`to `2.2.2` our Tempo instances could no longer access S3. We use AWS IRSA [^1] to provide AWS credentials.

The regression seems to be introduced by https://github.com/grafana/tempo/pull/2871
My current **guess** is the AWS SDK now prefers the EC2 instance role over IRSA.

**To Reproduce**
1. Deploy Tempo 2.2.1 on AWS EKS with S3 storage and IRSA authentication
2. Tempo should start and be able to access S3 as expected
3. Upgrade Tempo to 2.2.2 
4. Tempo should now crash during startup with S3 permission errors

**Expected behavior**
Tempo should continue to use the AWS IRSA provided credentials.

**Environment:**
 - Infrastructure: Kubernetes (AWS EKS)
 - Deployment tool: Helm (tempo-distributed - 1.6.3 - upgraded from 1.6.2)

**Additional Context**
Service logs (compactor):
```
level=info ts=2023-09-04T09:01:59.662782222Z caller=main.go:221 msg="initialising OpenTracing tracer"
level=info ts=2023-09-04T09:01:59.680278556Z caller=main.go:108 msg="Starting Tempo" version="(version=2.2.2, branch=HEAD, revision=5e18d78ba)"
level=error ts=2023-09-04T09:01:59.728222984Z caller=main.go:111 msg="error running Tempo" err="failed to init module services error initialising module: store: failed to create store unexpected error from ListObjects on <bucket_name>: Access Denied"
```

AWS environment variables in a running container:
```
$ env | grep -i aws
AWS_ROLE_ARN=arn:aws:iam::XXXXXXXXXXX:role/eks-development-v2-tempo
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
AWS_STS_REGIONAL_ENDPOINTS=regional
AWS_DEFAULT_REGION=eu-central-1
AWS_REGION=eu-central-1
```

Storage configuration (copied from `tempo-distributed` Helm values):
```yaml
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::XXXXXXXXXXX:role/eks-development-v2-tempo"

    storage:
      trace:
        backend: s3
        s3:
          bucket: <bucket_name>
          endpoint: s3.eu-central-1.amazonaws.com
          region: eu-central-1 # Added during troubleshooting
```

[^1]: https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

### PR DESCRIPTION
**Pull request by mapno**
**What this PR does**:

Fixes AWS authentication for IRSA.

PR #2889 was suppose to fix this but it didn't. Simply switching the chain flow up a bit resolves this issue without the need of if statements makes this all work again, which is what this PR does.

Removes config option `native_aws_auth_enabled`, as it's no longer necessary. If you were using this option, remove it from your config.

There are images publised for [amd64](https://hub.docker.com/layers/mapno/tempo/aws-cred-fix-amd64/images/sha256-68104b88e948534457c8a5dff8c95799f3a8b24f3936589501c6c6a42604fc48?context=repo) and [arm64](https://hub.docker.com/layers/mapno/tempo/aws-cred-fix-arm64/images/sha256-5e513e3fa7cf840753b54721781a04e353cb1911f9076a046c3ffa634fd9f39f?context=repo) architectures.

**Which issue(s) this PR fixes**:
Fixes #2888

**Checklist**
- [x] Tests updated
- [x] Documentation removed
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by ekristen** [comment]
Looks like this is replacing https://github.com/grafana/tempo/pull/2958 -- which is fine with me. 

The non-mocked test is doable if you have an AWS account that you can setup with GitHub and setup an Identity Provider in IAM. If not, no biggie.

+1 to all this, please merge as soon as possible.

**Comment by joe-elliott** [comment]
See comment for test images: https://github.com/grafana/tempo/pull/2958#issuecomment-1757602080

**Review by jdbaldry — COMMENTED** [review]
Docs changes look trivial and good to me.

File: tempodb/backend/s3/s3.go [hunk 1]
```diff
@@ -421,42 +422,47 @@ func (rw *readerWriter) readRange(ctx context.Context, objName string, offset in
...
+			Client: &http.Client{
+				Transport: http.DefaultTransport,
+			},
+			Endpoint: os.Getenv("TEST_IAM_ENDPOINT"),
+		}),
+	}
 
-	if cfg.NativeAWSAuthEnabled {
-		chain = []credentials.Provider{
-			wrapCredentialsProvider(NewAWSSDKAuth(cfg.Region)),
```
Comment (coufalja) [inline tempodb/backend/s3/s3.go:436]: You should be able to remove `NewAWSSDKAuth` and related tests as it should not be used anywhere else.

**Comment by coufalja** [comment]
Sorry for the delay but I can confirm that `mapno/tempo:aws-cred-fix-amd64` works as expected in our environment. (AWS IMSv1)

File: tempodb/backend/s3/s3.go (hunk 1 above)
Comment (mapno) [reply tempodb/backend/s3/s3.go:436]: Good point, removed!

**Review by knylander-grafana — COMMENTED** [review]
Thank you for removing doc that wasn't needed any more.

File: CHANGELOG.md [hunk 2]
```diff
@@ -78,6 +78,8 @@ defaults:
 * [BUGFIX] Moved empty root span substitution from `querier` to `query-frontend`. [#2671](https://github.com/grafana/tempo/issues/2671) (@galalen)
 * [BUGFIX] Correctly propagate ingester errors on the query path [#2935](https://github.com/grafana/tempo/issues/2935) (@joe-elliott)
 * [BUGFIX] Fix cases where empty filter {} wouldn't return expected results [#2498](https://github.com/grafana/tempo/issues/2498) (@mdisibio)
+* [BUGFIX] Reorder S3 credential chain and upgrade minio-go [#3006](https://github.com/grafana/tempo/pull/3006) (@ekristen, @mapno)
+    Removes config option `native_aws_auth_enabled`. If you were using this option, remove it from your config.
```
Comment (electron0zero) [inline CHANGELOG.md:82]: is this a breaking change? if yes, can we please mark it as breaking change here?

Comment (ekristen) [reply CHANGELOG.md:82]: Removing `native_aws_auth_enabled` if left in the config will cause a break due to how the config is parsed. I would suggest that perhaps we leave the config option in and write a log message if it's set that it's deprecated and remove it in the next major release.

Comment (ekristen) [reply CHANGELOG.md:82]: Leaving it in place and saying it's deprecated and is not used wouldn't hurt anything to prevent this from being a breaking change.

**Review by joe-elliott — APPROVED** [review]
Going to approve to unblock @mapno. I do agree with the comments that we need to mark a breaking change and it would be nice to parse the field and log a warning, but other than that this LGTM.

Thank you to @ekristen @coufalja @sberz and everyone else who helped us resolve this! Who knew that aws auth was so complicated :)

File: CHANGELOG.md (hunk 2 above)
Comment (mapno) [reply CHANGELOG.md]: Went with that approach, is nicer for users. Thanks!

File: tempodb/backend/s3/s3.go [hunk 3]
```diff
@@ -421,42 +422,47 @@ func (rw *readerWriter) readRange(ctx context.Context, objName string, offset in
...
 		}
 		return p
 	}
 
-	var chain []credentials.Provider
+	chain := []credentials.Provider{
+		wrapCredentialsProvider(&credentials.Static{
+			Value: credentials.Value{
+				AccessKeyID:     cfg.AccessKey,
+				SecretAccessKey: cfg.SecretKey.String(),
```
Comment (farodin91) [inline tempodb/backend/s3/s3.go:437]: @joe-elliott  I was able to provide the session token via code. now this isn't longer possible.

Comment (farodin91) [reply tempodb/backend/s3/s3.go:437]: https://github.com/grafana/tempo/pull/3144
