### PR TITLE
Ingester: Validate completed blocks

### LINKED ISSUE #4166: Reading footer of parquet file: error in rang e read from s3 backend 416 Requested Range Not Satisfiable
**Describe the bug**
Fails to fetch parquet objects from S3/Minio and get this error

```
level=warn ts=2024-10-10T12:12:25.647736726Z caller=server.go:2171 trace_id_unsampled=1fb525ccad3e46d6 msg="GET /api/search?q=%7B%7D&limit=20&spss=3&start=1728560545&end=1728562345 (500) 82.201572ms Response: \"reading footer of parquet file: error in rang
e read from s3 backend, bucket: tempo, objName: single-tenant/2f672840-f2cf-4348-a88a-e790bdfd4e95/data.parquet: 416 Requested Range Not Satisfiable\\n\" ws: false; Accept: application/json, text/plain, */*; Accept-Encoding: gzip, deflate; Accept-Language:
 en-GB,en-US;q=0.9,en;q=0.8,sv;q=0.7; User-Agent: Grafana/11.2.0; X-Forwarded-For: 10.98.37.156, 10.98.37.156, 10.39.34.196; X-Grafana-Org-Id: 1; X-Grafana-Referer: http://grafana.secondary.monitor.swedbank.test:3000/explore?schemaVersion=1&panes=%7B%22auq
%22:%7B%22datasource%22:%22adzvazqauaxvke%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22tempo%22,%22uid%22:%22adzvazqauaxvke%22%7D,%22queryType%22:%22traceqlSearch%22,%22limit%22:20,%22tableType%22:%22traces%22,%22filters%22:
%5B%7B%22id%22:%22f531af88%22,%22operator%22:%22%3D%22,%22scope%22:%22span%22%7D%5D%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D,%22qmp%22:%7B%22datasource%22:%22adzvazqauaxvke%22,%22queries%22:%5B%7B%22query%22:%226707b7fe2e1655e5
08238b8af5ea5948%22,%22queryType%22:%22traceql%22,%22refId%22:%22A%22,%22limit%22:20,%22tableType%22:%22traces%22%7D%5D,%22range%22:%7B%22from%22:%221728557049341%22,%22to%22:%221728560649341%22%7D%7D%7D&orgId=1; ""

```
**To Reproduce**
1. Start Tempo 2.6.0 with more or less default config.  
This is our config:

```

server:
  http_listen_port: 3100
  grpc_listen_port: 4310
  log_format: logfmt
  log_level: info

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  ring:
    kvstore:
      store: memberlist
    instance_interface_names:
      - ens160

compactor:
  compaction:
    block_retention: 48h
  ring:
    kvstore:
      store: memberlist
    instance_interface_names:
      - ens160

memberlist:
  abort_if_cluster_join_fails: false
  bind_port: 4311
  #bind_addr: []
  advertise_port: 4311
  cluster_label: ${CLUSTER_NAME}
  cluster_label_verification_disabled: false
  join_members:
    - ${SERVER_1}.sbcore.net:4311
    - ${SERVER_2}.sbcore.net:4311
    - ${SERVER_3}.sbcore.net:4311

metrics_generator:
  ring:
    kvstore:
      store: memberlist
    instance_interface_names:
      - ens160
  storage:
    path: /sb/env/data/mon/tempo/wal
  traces_storage:
    path: /sb/env/data/mon/tempo/traces
storage:
  trace:
    backend: s3
    s3:
      access_key: ${MINIO_USER}
      secret_key: ${MINIO_PW}
      bucket: tempo
      endpoint: localhost:7000
      insecure: true
    wal:
      path: /sb/env/data/mon/tempo/wal
querier:
  frontend_worker:
    frontend_address: 127.0.0.1:4310

overrides:
  defaults:
    metrics_generator:
      processors: 
        - service-graphs
        - span-metrics

usage_report:
  reporting_enabled: false

auth_enabled: false
multitenancy_enabled: false

```

**Environment:**
 - Bare-metal, 3 servers with Tempo 2.6.0 standalone (scalable-single-binary) with Minio sidekick loadbalancer
 -  Minio storage cluster MinIO VERSION  2024-10-02T17:50:41Z.
 - Bash scripts for installation and startup

**Additional Context**

This is how the files are organized in the tempo machine
```
p986_ga8632123_t@lx79590:/sb/env/logs/mon/tempo$ du -ah /sb/env/data/mon/tempo/
0       /sb/env/data/mon/tempo/wal/blocks/single-tenant
0       /sb/env/data/mon/tempo/wal/blocks
0       /sb/env/data/mon/tempo/wal/single-tenant/wal/00000000
0       /sb/env/data/mon/tempo/wal/single-tenant/wal
0       /sb/env/data/mon/tempo/wal/single-tenant/lock
0       /sb/env/data/mon/tempo/wal/single-tenant
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000001
4.0K    /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/meta.json
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000002
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000003
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000004
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000005
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000006
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000007
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000008
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000009
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000010
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000011
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000012
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000013
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000014
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000015
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000016
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000017
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000018
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000019
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000020
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000021
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000022
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000023
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000024
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000025
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000026
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000027
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000028
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000029
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000030
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000031
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000032
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000033
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000034
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000035
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000036
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000037
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000038
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000039
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000040
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000041
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000042
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000043
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000044
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000045
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000046
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000047
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000048
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000049
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000050
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000051
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000052
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000053
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000054
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000055
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000056
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000057
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000058
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000059
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000060
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000061
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000062
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000063
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000064
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000065
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000066
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000067
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000068
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000069
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000070
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000071
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000072
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000073
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000074
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000075
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000076
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000077
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000078
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000079
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000080
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000081
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000082
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000083
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000084
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000085
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000086
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000087
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000088
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000089
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000090
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000091
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000092
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000093
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000094
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000095
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000096
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000097
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000098
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000099
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000100
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000101
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000102
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000103
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000104
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000105
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000106
28K     /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000107
0       /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4/0000000108
3.0M    /sb/env/data/mon/tempo/wal/2f30f97e-d8bd-4adf-a24d-ad402b301b65+single-tenant+vParquet4
3.0M    /sb/env/data/mon/tempo/wal
0       /sb/env/data/mon/tempo/traces/single-tenant/blocks
0       /sb/env/data/mon/tempo/traces/single-tenant
0       /sb/env/data/mon/tempo/traces
3.0M    /sb/env/data/mon/tempo/
```

[tempo.log](https://github.com/user-attachments/files/17327825/tempo.log)

Image

### PR DESCRIPTION
**Pull request by joe-elliott**
**What this PR does**:
Adds a `Validate()` method to backend blocks and uses it in ingester startup to do basic confirmation of block health before reloading them. This prevents corrupt blocks from being loaded and eventually pushed to object storage.

**Which issue(s) this PR fixes**:
Fixes #4166 as near as we can tell. At least it covers the instance seen internally.

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: tempodb/encoding/vparquet4/block.go [hunk 1]
```diff
@@ -33,3 +38,40 @@ func newBackendBlock(meta *backend.BlockMeta, r backend.Reader) *backendBlock {
 func (b *backendBlock) BlockMeta() *backend.BlockMeta {
 	return b.meta
 }
+
+// Validate will do a basic sanity check of the state of the parquet file. This can be extended to do more checks in the future.
+// This method should lean towards being cost effective over complete.
+func (b *backendBlock) Validate(ctx context.Context) error {
```
Comment (javiermolinar) [inline tempodb/encoding/vparquet4/block.go:44]: I wonder if it would not be simpler trying to open the file directly with parquet-go:

```go
	o := []parquet.FileOption{
		parquet.SkipBloomFilters(true),
		parquet.SkipPageIndex(true),
		parquet.FileSchema(parquetSchema),
		parquet.FileReadMode(parquet.ReadModeAsync),
	}

	reader := NewBackendReaderAt(ctx, b.r, DataFileName, b.meta)
	_, err := parquet.OpenFile(reader, int64(b.meta.Size_), o...)
	if err != nil {
		return fmt.Errorf("failed to read parquet fike: %w", err)
	}
```

OpenFile seems to do essentially the same plus some other validations. Is this difference noticeable enough? Since this is at startup time maybe it isn't.

File: tempodb/encoding/vparquet4/block.go [hunk 2]
```diff
@@ -33,3 +38,40 @@ func newBackendBlock(meta *backend.BlockMeta, r backend.Reader) *backendBlock {
...
+	if b.meta == nil {
```
Comment (zalegrala) [inline tempodb/encoding/vparquet4/block.go:45]: Is there a way to reassemble this information from data on disk and still avoid paying the allocs on startup like you mention above?

**Review by zalegrala — APPROVED** [review]
Looks good to me.

File: tempodb/encoding/vparquet4/block.go (hunk 2 above)
Comment (joe-elliott) [reply tempodb/encoding/vparquet4/block.go:45]: possibly? what do you mean by "this information"?
