### PR TITLE
search/utils: added missing new intrinsic names to search/tags endpoint

### LINKED ISSUE #3714: Tags Endpoint: Incorrect intrinsics returned
**Describe the bug**
When querying the `/api/v2/tags` endpoint Tempo still returns the old intrinsic names.  In https://github.com/grafana/tempo/pull/3629 we added support for the new intrinsic names but forgot to swap over this endpoint:

> curl -H 'X-Scope-OrgID: 1' 'http://localhost:3100/tempo/api/v2/search/tags?scope=intrinsic'
{"scopes":[{"name":"intrinsic","tags":["duration","kind","name","rootName","rootServiceName","status","statusMessage","traceDuration"]}]}

Should return names like:

`span:duration`, `span:kind`.

While we're at it, let's add these two new intrinsics as well:

https://github.com/grafana/tempo/pull/3670

We should consider returning both the legacy and new values since we intend to support them both for the foreseeable future.

**Code changes**

This is the code that returns intrinsic tags:
https://github.com/grafana/tempo/blob/main/pkg/search/util.go#L57

Also confirm that this method works for the new intrinsic names:
https://github.com/grafana/tempo/blob/main/pkg/search/util.go#L31

### PR DESCRIPTION
**Pull request by ishanjain28**
**What this PR does**:

This PR adds new intrinsic names to the response of `/v2/search/tags` endpoint.

The response now looks like, 
```
{"scopes":[{"name":"intrinsic","tags":["duration","kind","name","rootName","rootServiceName","span:duration","span:kind","span:name","span:status","span:statusMessage","status","statusMessage","trace:rootName","trace:rootServiceName","traceDuration"]}]}
```

It is missing `trace:traceDuration`. I wasn't sure what to call it in the code ?

**Which issue(s) this PR fixes**:
Fixes #3714

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by ishanjain28** [comment]
Hi  @ie-pham, Requesting a review

File: pkg/traceql/enum_attributes.go [hunk 1]
```diff
@@ -89,6 +89,13 @@ const (
 
 	IntrinsicTraceID
 	IntrinsicSpanID
+	IntrinsicSpanStatus
```
Comment (ie-pham) [inline pkg/traceql/enum_attributes.go:92]: To differentiate perhaps we can do "ScopedIntrinsic-" instead of continuing the "Intrinsic" pattern? What do you think?

Comment (ishanjain28) [reply pkg/traceql/enum_attributes.go:92]: That sounds good to me, I'll make the change!

Comment (ishanjain28) [reply pkg/traceql/enum_attributes.go]: Made the changes, Requesting re-review.

**Comment by ie-pham** [comment]
Thank you for changing the prefix. Can you add `ScopedIntrinsicTraceDuration` now that it's not conflicting anymore?

**Comment by ishanjain28** [comment]
Added `trace:traceDuration`.

**Review by ie-pham — APPROVED** [review]
Awesome work! Thank you for contributing
