### PR TITLE
Parquet: Fix Combiner

### LINKED ISSUE #2057: [Grafana Cloud Traces] Traces search returns missing trace name and wrong duration
**Describe the bug**

Grafana Cloud Traces search return some traces with missing span name ("<root span not yet received>" or "") and wrong very short trace duration. 
In the search result screen, some traces are erraneous, some other are not, the errors change when we re execute the query.

See screenshot
image

**To Reproduce**

This problem can be reproduced instrumenting a SpringBoot App with Otel Java Auto Instr 1.21 send OTLP signals to Grafana Agent 0.31 sending signals to Grafana Cloud Traces, Logs, and Metrics (example [here](https://github.com/cyrille-leclerc/my-shopping-cart/tree/grafana)).

Another way to reproduce is the following
* Get a Grafana Cloud account
* Install Jenkins and the [Jenkins OpenTelemetry Plugin](https://plugins.jenkins.io/opentelemetry/) and a Grafana Agent 0.31 
* Configure 
   * Grafana Agent to sendd OTLP to Grafana Cloud Traces, Logs, and Metrics (ie Tempo, Loki, and Mimir) 
   * Jenkins to send OTLP signals to the Grafana Agent
   * Also send the traces to Jaeger for verification
* Create and run a Jenkins Pipeline similar to https://github.com/cyrille-leclerc/ecommerce-antifraud
* Verify in Grafana Cloud Explore the produced traces (eg search and `service.name=jenkins` and attribute `type="job"`

**Expected behavior**

Span name and duration are properly reported in the "search results view" and match the data reporter in the trace gantt viz screen

**Environment:**
 - Infrastructure: Grafana Cloud
 - Jenkins OpenTelemetry Plugin 2.10.1-SNAPSHOT (Otel Java SDK 1.19.0) or a plain Otel Java Instrumentation 1.21.0 with a Spring Boot application.

**Additional Context**

### PR DESCRIPTION
**Pull request by joe-elliott**
**What this PR does**:
The Parquet combiner used during compaction and when combining multiple traces on query does not correctly coalesce root level trace data. This fixes it.

**Which issue(s) this PR fixes**:
Likely this fixes #2057. At  least it would certainly contribute to it.

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: tempodb/encoding/vparquet/combiner.go [hunk 1]
```diff
@@ -99,6 +99,21 @@ func (c *Combiner) ConsumeWithFinal(tr *Trace, final bool) (spanCount int) {
 		return
 	}
 
+	// coalese root level information
+	if tr.EndTimeUnixNano > c.result.EndTimeUnixNano || c.result.EndTimeUnixNano == 0 {
```
Comment (mapno) [inline tempodb/encoding/vparquet/combiner.go:103]:
```suggestion
	if tr.EndTimeUnixNano > c.result.EndTimeUnixNano {
```

I think this covers it.

**Review by mapno — APPROVED** [review]
LGTM
