### PR TITLE
Prune in-memory blocks from missing tenants

### LINKED ISSUE #285: Blocklist never prunes missing tenants
**Describe the bug**
If a tenant disappears (say by deleting all of its blocks manually from the backend) the internal in memory blocklist will never be updated to indicate this.

**To Reproduce**
1. Send spans to tempo
2. Let some blocks build up
3. Stop sending spans to tempo
4. Delete the tenant level folder on the backend
5. Note that the tempodb_blocklist_length value doesn't go to 0.

**Expected behavior**
Blocks should be pruned from the in memory blocklist.

**Environment:**

**Additional Context**
This is b/c the `pollBlocklist` method in tempodb updates the blocklist of any tenant it finds, but if it fails to find the tenant it does nothing.

### PR DESCRIPTION
**Pull request by dgzlopes**
**What this PR does**:
If a tenant disappears blocks are pruned from the in-memory blocklist.

**Which issue(s) this PR fixes**:
Fixes #285

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: tempodb/tempodb.go [hunk 1]
```diff
@@ -382,6 +382,11 @@ func (rw *readerWriter) pollBlocklist() {
 		if err != nil {
 			metricBlocklistErrors.WithLabelValues(tenantID).Inc()
 			level.Error(rw.logger).Log("msg", "error polling blocklist", "tenantID", tenantID, "err", err)
+			rw.blockListsMtx.Lock()
+			delete(rw.blockLists, tenantID)
+			delete(rw.compactedBlockLists, tenantID)
+			rw.blockListsMtx.Unlock()
```
Comment (annanay25) [inline tempodb/tempodb.go:388]: Should this be part of the `err != nil` check? The call could error out for a number of reasons. And a failed call should not end up emptying the in-memory blocklist. Rather, this should be under a check `len(blockIDs) == 0`.

File: tempodb/tempodb.go [hunk 2]
```diff
@@ -382,6 +382,11 @@ func (rw *readerWriter) pollBlocklist() {
...
+			level.Error(rw.logger).Log("msg", "deleted in-memory blocklists", "tenantID", tenantID)
```
Comment (annanay25) [inline tempodb/tempodb.go:389]: The message sounds like a warning, if its error, it should detail the error, if performing a protective action, log as a warning.

**Review by annanay25 — DISMISSED** [review]
Thanks for working on this @dgzlopes! I've left some comments.

File: tempodb/tempodb.go (hunk 2 above)
Comment (joe-elliott) [reply tempodb/tempodb.go:389]: let's just go for info.  there's nothing error or warning about clearing a blocklist.  this will be expected behavior.

**Comment by joe-elliott** [comment]
To add to Annanay's comments, I would like a test that covers this.  Please just ask if you'd like some guidance on building a test, I know they're a little intense at the moment.

**Comment by dgzlopes** [comment]
Moved the code into a `len(blockIDs) == 0` block and changed the log level.

Okey @joe-elliott!

I'm diving into the tests, and well, they look fun. I'll `try` to add the coverage for this PR. If I'm blocked I'll ask for help :smile:

**Comment by dgzlopes** [comment]
Added a test. I'm not sure if it's OK... it's my first test in Go :smile: 

I re-used [TestRetention](https://github.com/grafana/tempo/blob/4edd1fe284bb3a564a14328bbfc217c3d415a739/tempodb/tempodb_test.go#L124) code, but this time before calling `pollBlocklist()` I remove the `testTenantID` trace folder. Then, I check if the in-memory blocklists still have the blocks.

File: tempodb/tempodb_test.go [hunk 3]
```diff
@@ -175,6 +175,58 @@ func TestRetention(t *testing.T) {
...
+	assert.NoError(t, err)
+
+	rw := r.(*readerWriter)
+
+	os.RemoveAll(tempDir + "/traces/" + testTenantID)
+
+	// poll
+	rw.pollBlocklist()
+
+	assert.Len(t, rw.blockLists[testTenantID], 0)
```
Comment (joe-elliott) [inline tempodb/tempodb_test.go:226]: change this to `_, ok := rw.blockLists[testTenantID]` and confirm that ok is false.

File: tempodb/tempodb_test.go [hunk 4]
```diff
@@ -175,6 +175,58 @@ func TestRetention(t *testing.T) {
...
+
+	complete, err := head.Complete(wal, &mockSharder{})
+	assert.NoError(t, err)
+	blockID = complete.BlockMeta().BlockID
+
+	err = w.WriteBlock(context.Background(), complete)
+	assert.NoError(t, err)
+
+	rw := r.(*readerWriter)
+
```
Comment (joe-elliott) [inline tempodb/tempodb_test.go:220]: `rw.pollBlocklist()` here and confirm that testTenantID has one block in its blocklist.

**Review by joe-elliott — CHANGES_REQUESTED** [review]
Nice work on the tests.  Had a couple of suggestions for improvements and it looks like the linter is mad at you.

File: tempodb/tempodb.go [hunk 5]
```diff
@@ -383,6 +383,13 @@ func (rw *readerWriter) pollBlocklist() {
 			metricBlocklistErrors.WithLabelValues(tenantID).Inc()
 			level.Error(rw.logger).Log("msg", "error polling blocklist", "tenantID", tenantID, "err", err)
 		}
+		if len(blockIDs) == 0 {
```
Comment (joe-elliott) [inline tempodb/tempodb.go:386]: oh, yikes, I missed this but this is in the wrong spot.  This should be down around line 434.  If, at that point, the len(blocklist) == 0 then we should delete from the map.

Also, the compactedBlocklist and normal blocklist need to be handled independently.  It's possible a tenant will have no normal blocks, but still have compacted blocks.

Comment (joe-elliott) [reply tempodb/tempodb.go:386]: Ok after further review and an offline discussion with @dgzlopes it appears this functionality actually needs to be line ~379.

In an object storage system like s3 or gcs there are no "folders" per se, just objects with a key path.  In this case if there are no objects there will be no tenant.  So, after retrieving the tenants on line 374 we need to check and remove every tenant in the blocklist maps that are not in the tenant list.

File: tempodb/tempodb.go [hunk 6]
```diff
@@ -377,6 +377,29 @@ func (rw *readerWriter) pollBlocklist() {
...
+
+	for tenantID := range rw.compactedBlockLists {
+		if _, present := tenantSet[tenantID]; !present {
+			rw.blockListsMtx.Lock()
+			delete(rw.compactedBlockLists, tenantID)
+			rw.blockListsMtx.Unlock()
+			level.Info(rw.logger).Log("msg", "deleted in-memory compacted blocklists", "tenantID", tenantID)
+		}
+	}
+
```
Comment (dgzlopes) [inline tempodb/tempodb.go:402]: I'm not sure if my approach is idiomatic!

I created a tenantSet from the backendTenants map. Later I loop over all the tenants on the in-memory blocklists, and If they don't exist on the tenantSet, I remove them.

File: tempodb/tempodb.go [hunk 7]
```diff
@@ -544,3 +546,28 @@ func (rw *readerWriter) compactedBlocklist(tenantID string) []*encoding.Compacte
 
 	return copiedBlocklist
 }
+
```
Comment (dgzlopes) [inline tempodb/tempodb.go:549]: I'm not sure if my approach is idiomatic!

I created a tenantSet from the backendTenants slide. Later I loop over all the tenants on the in-memory blocklists, and If they don't exist on the tenantSet, I remove them.

File: tempodb/tempodb.go [hunk 8]
```diff
@@ -544,3 +546,28 @@ func (rw *readerWriter) compactedBlocklist(tenantID string) []*encoding.Compacte
...
+func (rw *readerWriter) cleanMissingTenants(tenants []string) {
+	tenantSet := make(map[string]bool)
```
Comment (joe-elliott) [inline tempodb/tempodb.go:551]: nit:  `map[string]struct{}`

File: tempodb/tempodb.go [hunk 9]
```diff
@@ -544,3 +546,28 @@ func (rw *readerWriter) compactedBlocklist(tenantID string) []*encoding.Compacte
 
 	return copiedBlocklist
 }
+
+func (rw *readerWriter) cleanMissingTenants(tenants []string) {
```
Comment (joe-elliott) [inline tempodb/tempodb.go:550]: can we write some tests that target this method directly?  use a slice of test cases pattern.

**Review by joe-elliott — CHANGES_REQUESTED** [review]
Basically just looking for some tests directly targeting the `cleanMissingTenants` method.  Leave the existing test and add a `TestCleanMissingTenants()` test that directly exercises this method.

After that should be ready to go!

**Comment by dgzlopes** [comment]
Thanks a lot for the patience and the exhaustive review @joe-elliott :)

Fixed the nit and added the test for `cleanMissingTenants`.

**Review by joe-elliott — APPROVED** [review]
nice work @dgzlopes 

Thanks!
