### PR TITLE
Issue 4632: fix exemplars calculation

### LINKED ISSUE #4632: Query exemplars field not respected
**Describe the bug**
When running a TraceQL metrics query with exemplars enabled, the `exemplars` query field value is not respected by Tempo, it always returns the amount of exemplars decided internally in Tempo. 

**To Reproduce**
1. Start Tempo (2.7.0)
2. Run a metrics query `{} | rate()` and set the exemplars field as `3`, for example

**Expected behavior**
In the example above I would expect to only receive 3 exemplars, but receive more.

### PR DESCRIPTION
**Pull request by ruslan-mikhailov**
**What this PR does**:

- Request at least 1 exemplar per shard
- Correct exemplars calculation: with totalRecords > pages, page should be the numerator and total records the denominator
- Correct calculation of required pages per request (fix for case `small block`)

**Which issue(s) this PR fixes**:
Fixes #4632

**Checklist**

- [x] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: modules/frontend/metrics_query_range_sharder_test.go [hunk 1]
```diff
@@ -0,0 +1,194 @@
...
+func TestBuildBackendRequestsExemplarsOneBlock(t *testing.T) {
+	// Create the test sharder with exemplars enabled
+	sharder := &queryRangeSharder{
+		logger: log.NewNopLogger(),
+		cfg: QueryRangeSharderConfig{
+			MaxExemplars: 100,
+		},
+	}
+	tenantID := "test-tenant"
+	targetBytesPerRequest := 1000
```
Comment (zalegrala) [inline modules/frontend/metrics_query_range_sharder_test.go:47]: Leaving this static I suppose is desired because the test cases have blocksizes and records above and below this number to test each side of the calculation.

**Review by zalegrala — APPROVED** [review]
This looks correct to me.  Nice work on the tests.

**Review by mapno — APPROVED** [review]
LGTM

File: modules/frontend/metrics_query_range_sharder_test.go (hunk 1 above)
Comment (ruslan-mikhailov) [reply modules/frontend/metrics_query_range_sharder_test.go:47]: Exactly

**Comment by ruslan-mikhailov** [comment]
\+ rebase from latest master to resolve merge conflicts
