### PR TITLE
Issue 4896 traceql metrics fixes

### LINKED ISSUE #4896: TraceQL Metrics lose traces
**Describe the bug**
Adding TraceQL Metrics check (https://github.com/grafana/tempo/pull/4886) to vulture results in 20% of cases where a trace cannot be found.
Example:
TraceQL `{.vulture-process-0 = "EFvnOV"}` finds a trace:
Image
TraceQL `{.vulture-process-0 = "EFvnOV"} | count_over_time()` sees no results:
Image

**To Reproduce**
Use branch: [traceql-metrics-bug-reproduce](https://github.com/ruslan-mikhailov/tempo/tree/traceql-metrics-bug-reproduce)
It uses vulture to check TraceQL metric by query `{.random_attr="value"} | count_over_time()`. This branch also contains debug logs for every request and response.

1. Build vulture by `make docker-tempo-vulture`
2. Run docker-compose file: `example/docker-compose/distributed`
3. Wait for 5-10 minutes

**Expected behavior**
No "not found by metrics" errors. This can be checked in logs, but it is easier to open local Grafana Explore and run the following:
```
sum(rate(tempo_vulture_trace_error_total{}[$__rate_interval])) by (error) / ignoring (error) group_left sum(rate(tempo_vulture_trace_total{}[$__rate_interval]))
```

Actual results: about 20% of TraceQL metrics checks are failing.

**Environment:**
Locally, docker compose

**Additional Context**
-

### PR DESCRIPTION
**Pull request by ruslan-mikhailov**
## What this PR does

Start and end of the trace in generator are converted to seconds, dropping the fractional part.
```go
// Convert from unix nanos to unix seconds
startSeconds := uint32(start / uint64(time.Second))
endSeconds := uint32(end / uint64(time.Second))

err := p.headBlock.AppendTrace(id, tr, startSeconds, endSeconds, p.Cfg.AdjustTimeRangeForSlack)
```
Additionally, blocks' start and end times are in seconds.

image

### Bug 1
Search in blocks was exclusive, but it should have included both edges. See https://github.com/grafana/tempo/blob/a1ab3f911f9656fc5a82e7f1bd76eea4494c7bc0/modules/frontend/frontend.go#L361 as a reference
### Bug 2. Losing the last trace in the block. 

image

It filters here:
```
			if e.checkTime {
				st := s.StartTimeUnixNanos()
				if st < e.start || st >= e.end {
					continue
				}
			}
```

To fix it, need to include the right border, but _only_ when request's time range fully includes the right edge of the block

### Bug 3. Lonely trace in a block. 
It is possible to have a block with start==end, it can be reproduced if only one trace was pushed and flushed.

This results in skipping this block
```go
func (e *MetricsEvaluator) Do(ctx context.Context, f SpansetFetcher, fetcherStart, fetcherEnd uint64) error {
	// Make a copy of the request so we can modify it.
	storageReq := *e.storageReq

	if fetcherStart > 0 && fetcherEnd > 0 &&
		fetcherStart != fetcherEnd {
			overlap := timeRangeOverlap(e.start, e.end, fetcherStart, fetcherEnd)
			if overlap == 0.0 { // <------ overlap will be zero
				// This shouldn't happen but might as well check.
				// No overlap == nothing to do
				return nil
			}
```
 
### Bug 4. Exemplars are not filtered
```go
		for _, s := range ss.Spans {
			if e.checkTime {
				st := s.StartTimeUnixNanos()
				if st < e.start || st >= e.end {
					continue
				}
			}

			e.spansTotal++

			e.metricsPipeline.observe(s)
		}

		if len(ss.Spans) > 0 && e.sampleExemplar(ss.TraceID) {
			e.metricsPipeline.observeExemplar(ss.Spans[rand.Intn(len(ss.Spans))])
		}
```
This results in including traces outside of the requested time range

image

## Which issue(s) this PR fixes
Fixes https://github.com/grafana/tempo/issues/4896

### Vulture
It was checked by https://github.com/grafana/tempo/pull/4886

1. one binary docker compose (https://github.com/grafana/tempo/tree/main/example/docker-compose/local)
2. distributed docker compose (https://github.com/grafana/tempo/tree/main/example/docker-compose/distributed)
3. rhythm docker compose (https://github.com/grafana/tempo/tree/main/example/docker-compose/ingest-storage)
4. long run in k8s with rhythm enabled
image

### Autotest
1. e2e test for a single trace
2. unit test for 2 traces to test border conditions

## Checklist
- [x] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: pkg/traceql/engine_metrics.go [hunk 1]
```diff
@@ -1047,7 +1054,8 @@ func (e *MetricsEvaluator) Do(ctx context.Context, f SpansetFetcher, fetcherStar
 
 		e.mtx.Lock()
 
-		for _, s := range ss.Spans {
+		filteredSpansIndex := make([]int, 0, len(ss.Spans)) // optimistic preallocation
```
Comment (mdisibio) [inline pkg/traceql/engine_metrics.go:1057]: Need to watch performance here of maintaining another slice for every span.  A few thoughts: it is worth losing some exemplar "fairness" here in order to keep performance high if needed, and also check `e.sampleExemplar` earlier to skip over extra work when we already have enough exemplars.   I have a feeling that it would be faster to iterate `ss.Spans` twice in a second pass looking for exemplars, than to populate another slice.

Comment (ruslan-mikhailov) [reply pkg/traceql/engine_metrics.go]: Applied reservoir sampling algorithm. Benchmark results:

// BenchmarkExperimentOriginal-12    	  538930	      2220 ns/op	       0 B/op	       0 allocs/op
// BenchmarkExperimentA-12    	  480423	      2505 ns/op	     896 B/op	       1 allocs/op
// BenchmarkExperimentB-12    	  468480	      2255 ns/op	       0 B/op	       0 allocs/op
// BenchmarkExperimentC-12    	  526160	      2271 ns/op	       0 B/op	       0 allocs/op

Let me know if I need to move the optimisation any forward.

<details>
  <summary>Source code of the benchmark</summary>

  ```go
func targetC(e *MetricsEvaluator, spans []Span) {
	var validSpansCount int
	var randomSpanIndex int

	needExemplar := e.maxExemplars > 0 && e.sampleExemplar(spans[0].ID())

	for i, s := range spans {
		if e.checkTime {
			st := s.StartTimeUnixNanos()
			if st < e.start || st >= e.end {
				continue
			}
		}

		validSpansCount++
		e.metricsPipeline.observe(s)

		if !needExemplar {
			continue
		}

		if needExemplar && (validSpansCount == 1 || randv1.Intn(validSpansCount) == 0) {
			randomSpanIndex = i
		}
	}
	e.spansTotal += uint64(validSpansCount)

	if needExemplar && validSpansCount > 0 {
		e.metricsPipeline.observeExemplar(spans[randomSpanIndex])
	}
}
  ```
  
</details>

Comment (ruslan-mikhailov) [reply pkg/traceql/engine_metrics.go]: Experimentation proof that the probability distribution is flat:

```python
>>> def pickme(limit):
...     res = 0
...     for ii in range(limit):
...         if random.randint(0, ii) == 0:
...             res = ii
...     return res
...     
>>> c = Counter()

>>> for i in range(1000000):
...     c[pickme(100)] += 1
...     
>>> c
Counter({27: 10378, 18: 10311, 79: 10307, 69: 10288, 67: 10278, 82: 10275, 92: 10259, 6: 10256, 73: 10243, 34: 10224, 83: 10219, 31: 10210, 43: 10210, 53: 10207, 21: 10199, 36: 10193, 14: 10187, 17: 10187, 46: 10183, 99: 10182, 98: 10170, 7: 10165, 10: 10160, 71: 10159, 4: 10156, 64: 10153, 76: 10151, 48: 10149, 35: 10145, 41: 10145, 59: 10141, 63: 10138, 51: 10137, 72: 10137, 29: 10137, 84: 10136, 26: 10135, 42: 10133, 13: 10131, 45: 10131, 39: 10124, 55: 10119, 38: 10119, 40: 10119, 85: 10115, 1: 10112, 81: 10104, 47: 10102, 5: 10101, 15: 10099, 89: 10095, 61: 10087, 23: 10086, 22: 10086, 86: 10083, 93: 10082, 95: 10082, 28: 10082, 16: 10080, 94: 10079, 96: 10077, 32: 10076, 97: 10074, 77: 10073, 37: 10071, 65: 10069, 60: 10066, 9: 10064, 30: 10061, 75: 10058, 74: 10054, 3: 10053, 57: 10050, 68: 10050, 25: 10049, 33: 10045, 62: 10042, 56: 10040, 49: 10038, 78: 10036, 8: 10036, 88: 10033, 19: 10025, 0: 10020, 2: 10011, 90: 10008, 54: 9998, 70: 9997, 50: 9991, 91: 9987, 44: 9977, 24: 9977, 12: 9965, 52: 9928, 11: 9921, 87: 9921, 80: 9914, 58: 9899, 66: 9861, 20: 9724})
```

**Review by mdisibio — COMMENTED** [review]
Good changes, and I like the sampling algorithm.  It's hard to tell the overall impact to queries from the direct benchmarks numbers you have provided.  Can you try doing a benchstat comparison using the `BenchmarkBackendBlockQueryRange`?

File: pkg/traceql/engine_metrics.go (hunk 1 above)
Comment (ruslan-mikhailov) [reply pkg/traceql/engine_metrics.go]: Answer to https://github.com/grafana/tempo/pull/4962#pullrequestreview-2749687864 .

For a ~500mb block, the results are quite the same, the only significant difference is that the unoptimised solution requires more allocations. Baseline is code from main branch.

<details>
  <summary>benchstat</summary>

```
goos: darwin
goarch: arm64
pkg: github.com/grafana/tempo/tempodb/encoding/vparquet4
cpu: Apple M4 Pro
                                                                                                          │  main.txt   │            optimised.txt            │           unoptimised.txt           │
                                                                                                          │   sec/op    │   sec/op     vs base                │   sec/op     vs base                │
BackendBlockQueryRange/{}_|_rate()/5-12                                                                     12.61 ± ∞ ¹   12.51 ± ∞ ¹       ~ (p=1.000 n=1) ²   12.63 ± ∞ ¹       ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{}_|_rate()_by_(name)/5-12                                                           20.22 ± ∞ ¹   19.46 ± ∞ ¹       ~ (p=1.000 n=1) ²   19.99 ± ∞ ¹       ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{}_|_rate()_by_(resource.service.name)/5-12                                          17.12 ± ∞ ¹   16.50 ± ∞ ¹       ~ (p=1.000 n=1) ²   16.85 ± ∞ ¹       ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{}_|_rate()_by_(span.http.url)/5-12                                                  27.09 ± ∞ ¹   26.27 ± ∞ ¹       ~ (p=1.000 n=1) ²   27.10 ± ∞ ¹       ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{resource.service.name=`loki-ingester`}_|_rate()/5-12                                2.115 ± ∞ ¹   2.020 ± ∞ ¹       ~ (p=1.000 n=1) ²   2.155 ± ∞ ¹       ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{span.http.host_!=_``_&&_span.http.flavor=`2`}_|_rate()_by_(span.http.flavor)/5-12   7.618 ± ∞ ¹   8.031 ± ∞ ¹       ~ (p=1.000 n=1) ²   7.776 ± ∞ ¹       ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{status=error}_|_rate()/5-12                                                         2.276 ± ∞ ¹   2.261 ± ∞ ¹       ~ (p=1.000 n=1) ²   2.291 ± ∞ ¹       ~ (p=1.000 n=1) ²
geomean                                                                                                     8.875         8.732        -1.61%                   8.901        +0.29%
¹ need >= 6 samples for confidence interval at level 0.95
² need >= 4 samples to detect a difference at alpha level 0.05

                                                                                                          │  main.txt   │            optimised.txt            │           unoptimised.txt           │
                                                                                                          │  MB_IO/op   │  MB_IO/op    vs base                │  MB_IO/op    vs base                │
BackendBlockQueryRange/{}_|_rate()/5-12                                                                     22.58 ± ∞ ¹   22.58 ± ∞ ¹       ~ (p=1.000 n=1) ²   22.58 ± ∞ ¹       ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{}_|_rate()_by_(name)/5-12                                                           27.13 ± ∞ ¹   27.13 ± ∞ ¹       ~ (p=1.000 n=1) ²   27.13 ± ∞ ¹       ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{}_|_rate()_by_(resource.service.name)/5-12                                          23.16 ± ∞ ¹   23.16 ± ∞ ¹       ~ (p=1.000 n=1) ²   23.16 ± ∞ ¹       ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{}_|_rate()_by_(span.http.url)/5-12                                                  24.83 ± ∞ ¹   24.83 ± ∞ ¹       ~ (p=1.000 n=1) ²   24.83 ± ∞ ¹       ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{resource.service.name=`loki-ingester`}_|_rate()/5-12                                23.16 ± ∞ ¹   23.16 ± ∞ ¹       ~ (p=1.000 n=1) ²   23.16 ± ∞ ¹       ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{span.http.host_!=_``_&&_span.http.flavor=`2`}_|_rate()_by_(span.http.flavor)/5-12   70.74 ± ∞ ¹   70.74 ± ∞ ¹       ~ (p=1.000 n=1) ²   70.74 ± ∞ ¹       ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{status=error}_|_rate()/5-12                                                         24.35 ± ∞ ¹   24.35 ± ∞ ¹       ~ (p=1.000 n=1) ²   24.35 ± ∞ ¹       ~ (p=1.000 n=1) ²
geomean                                                                                                     28.16         28.16        +0.00%                   28.16        +0.00%
¹ need >= 6 samples for confidence interval at level 0.95
² all samples are equal

                                                                                                          │   main.txt   │            optimised.txt             │           unoptimised.txt            │
                                                                                                          │   spans/op   │   spans/op    vs base                │   spans/op    vs base                │
BackendBlockQueryRange/{}_|_rate()/5-12                                                                     4.736M ± ∞ ¹   4.736M ± ∞ ¹       ~ (p=1.000 n=1) ²   4.736M ± ∞ ¹       ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{}_|_rate()_by_(name)/5-12                                                           4.736M ± ∞ ¹   4.736M ± ∞ ¹       ~ (p=1.000 n=1) ²   4.736M ± ∞ ¹       ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{}_|_rate()_by_(resource.service.name)/5-12                                          4.736M ± ∞ ¹   4.736M ± ∞ ¹       ~ (p=1.000 n=1) ²   4.736M ± ∞ ¹       ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{}_|_rate()_by_(span.http.url)/5-12                                                  4.736M ± ∞ ¹   4.736M ± ∞ ¹       ~ (p=1.000 n=1) ²   4.736M ± ∞ ¹       ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{resource.service.name=`loki-ingester`}_|_rate()/5-12                                340.6k ± ∞ ¹   340.6k ± ∞ ¹       ~ (p=1.000 n=1) ²   340.6k ± ∞ ¹       ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{span.http.host_!=_``_&&_span.http.flavor=`2`}_|_rate()_by_(span.http.flavor)/5-12   3.262k ± ∞ ¹   3.262k ± ∞ ¹       ~ (p=1.000 n=1) ²   3.262k ± ∞ ¹       ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{status=error}_|_rate()/5-12                                                         124.2k ± ∞ ¹   124.2k ± ∞ ¹       ~ (p=1.000 n=1) ²   124.2k ± ∞ ¹       ~ (p=1.000 n=1) ²
geomean                                                                                                     683.1k         683.1k        +0.00%                   683.1k        +0.00%
¹ need >= 6 samples for confidence interval at level 0.95
² all samples are equal

                                                                                                          │   main.txt   │            optimised.txt             │           unoptimised.txt            │
                                                                                                          │   spans/s    │   spans/s     vs base                │   spans/s     vs base                │
BackendBlockQueryRange/{}_|_rate()/5-12                                                                     375.7k ± ∞ ¹   378.6k ± ∞ ¹       ~ (p=1.000 n=1) ²   375.1k ± ∞ ¹       ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{}_|_rate()_by_(name)/5-12                                                           234.2k ± ∞ ¹   243.4k ± ∞ ¹       ~ (p=1.000 n=1) ²   236.9k ± ∞ ¹       ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{}_|_rate()_by_(resource.service.name)/5-12                                          276.7k ± ∞ ¹   287.0k ± ∞ ¹       ~ (p=1.000 n=1) ²   281.1k ± ∞ ¹       ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{}_|_rate()_by_(span.http.url)/5-12                                                  174.8k ± ∞ ¹   180.3k ± ∞ ¹       ~ (p=1.000 n=1) ²   174.8k ± ∞ ¹       ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{resource.service.name=`loki-ingester`}_|_rate()/5-12                                161.0k ± ∞ ¹   168.6k ± ∞ ¹       ~ (p=1.000 n=1) ²   158.1k ± ∞ ¹       ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{span.http.host_!=_``_&&_span.http.flavor=`2`}_|_rate()_by_(span.http.flavor)/5-12    428.2 ± ∞ ¹    406.2 ± ∞ ¹       ~ (p=1.000 n=1) ²    419.5 ± ∞ ¹       ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{status=error}_|_rate()/5-12                                                         54.55k ± ∞ ¹   54.91k ± ∞ ¹       ~ (p=1.000 n=1) ²   54.19k ± ∞ ¹       ~ (p=1.000 n=1) ²
geomean                                                                                                     76.97k         78.23k        +1.63%                   76.75k        -0.29%
¹ need >= 6 samples for confidence interval at level 0.95
² need >= 4 samples to detect a difference at alpha level 0.05

                                                                                                          │   main.txt    │             optimised.txt             │            unoptimised.txt            │
                                                                                                          │     B/op      │     B/op       vs base                │     B/op       vs base                │
BackendBlockQueryRange/{}_|_rate()/5-12                                                                     485.4Mi ± ∞ ¹   485.1Mi ± ∞ ¹       ~ (p=1.000 n=1) ²   536.8Mi ± ∞ ¹       ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{}_|_rate()_by_(name)/5-12                                                           662.9Mi ± ∞ ¹   659.0Mi ± ∞ ¹       ~ (p=1.000 n=1) ²   707.2Mi ± ∞ ¹       ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{}_|_rate()_by_(resource.service.name)/5-12                                          644.4Mi ± ∞ ¹   640.2Mi ± ∞ ¹       ~ (p=1.000 n=1) ²   688.3Mi ± ∞ ¹       ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{}_|_rate()_by_(span.http.url)/5-12                                                  873.2Mi ± ∞ ¹   869.8Mi ± ∞ ¹       ~ (p=1.000 n=1) ²   915.7Mi ± ∞ ¹       ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{resource.service.name=`loki-ingester`}_|_rate()/5-12                                170.1Mi ± ∞ ¹   177.4Mi ± ∞ ¹       ~ (p=1.000 n=1) ²   179.8Mi ± ∞ ¹       ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{span.http.host_!=_``_&&_span.http.flavor=`2`}_|_rate()_by_(span.http.flavor)/5-12   184.7Mi ± ∞ ¹   184.7Mi ± ∞ ¹       ~ (p=1.000 n=1) ²   176.1Mi ± ∞ ¹       ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{status=error}_|_rate()/5-12                                                         79.23Mi ± ∞ ¹   84.01Mi ± ∞ ¹       ~ (p=1.000 n=1) ²   79.79Mi ± ∞ ¹       ~ (p=1.000 n=1) ²
geomean                                                                                                     332.6Mi         336.6Mi        +1.20%                   346.9Mi        +4.29%
¹ need >= 6 samples for confidence interval at level 0.95
² need >= 4 samples to detect a difference at alpha level 0.05

                                                                                                          │   main.txt   │            optimised.txt             │            unoptimised.txt            │
                                                                                                          │  allocs/op   │  allocs/op    vs base                │  allocs/op    vs base                 │
BackendBlockQueryRange/{}_|_rate()/5-12                                                                     1.754M ± ∞ ¹   1.753M ± ∞ ¹       ~ (p=1.000 n=1) ²   2.347M ± ∞ ¹        ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{}_|_rate()_by_(name)/5-12                                                           3.145M ± ∞ ¹   3.144M ± ∞ ¹       ~ (p=1.000 n=1) ²   3.744M ± ∞ ¹        ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{}_|_rate()_by_(resource.service.name)/5-12                                          3.121M ± ∞ ¹   3.118M ± ∞ ¹       ~ (p=1.000 n=1) ²   3.713M ± ∞ ¹        ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{}_|_rate()_by_(span.http.url)/5-12                                                  5.822M ± ∞ ¹   5.825M ± ∞ ¹       ~ (p=1.000 n=1) ²   6.417M ± ∞ ¹        ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{resource.service.name=`loki-ingester`}_|_rate()/5-12                                621.7k ± ∞ ¹   621.5k ± ∞ ¹       ~ (p=1.000 n=1) ²   624.1k ± ∞ ¹        ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{span.http.host_!=_``_&&_span.http.flavor=`2`}_|_rate()_by_(span.http.flavor)/5-12   151.6k ± ∞ ¹   151.2k ± ∞ ¹       ~ (p=1.000 n=1) ²   154.7k ± ∞ ¹        ~ (p=1.000 n=1) ²
BackendBlockQueryRange/{status=error}_|_rate()/5-12                                                         127.9k ± ∞ ¹   127.6k ± ∞ ¹       ~ (p=1.000 n=1) ²   188.1k ± ∞ ¹        ~ (p=1.000 n=1) ²
geomean                                                                                                     1.027M         1.026M        -0.09%                   1.210M        +17.79%
¹ need >= 6 samples for confidence interval at level 0.95
² need >= 4 samples to detect a difference at alpha level 0.05
```

</details>

File: pkg/traceql/engine_metrics.go [hunk 2]
```diff
@@ -86,11 +86,16 @@ func IntervalOfMs(tsmills int64, start, end, step uint64) int {
...
-// TrimToOverlap returns the aligned overlap between the two given time ranges. If the request
+// TrimToBlockOverlap returns the aligned overlap between the given time and block ranges. If the request
 // is instant, then will return and updated step to match to the new time range.
-func TrimToOverlap(start1, end1, step, start2, end2 uint64) (uint64, uint64, uint64) {
+// It assumes that the blockEnd is aligned to seconds.
+func TrimToBlockOverlap(start1, end1, step uint64, blockStart, blockEnd time.Time) (uint64, uint64, uint64) {
 	wasInstant := end1-start1 == step
 
+	start2 := uint64(blockStart.UnixNano())
+	blockEnd = blockEnd.Add(time.Second) // Add 1 second to include the last second of the block
```
[the remark this answers is not in the document]
Comment (ruslan-mikhailov) [reply pkg/traceql/engine_metrics.go]: Added a little bit more comments. Let me know if I need to explain in very detail

**Review by mdisibio — APPROVED** [review]
