### PR TITLE
fix: bring back content-type header

### LINKED ISSUE #4121: Empty Content-Type header from search endpoint
**Describe the bug**

There is a difference in the headers for `Content-Type` when calling `/api/search` between version `2.5.0` and `v2.6.0`

`grafana/otel-lgtm:0.7.2` uses tempo `2.5.0`

```
HTTP/1.1 200 OK
Content-Length: 698
Content-Security-Policy: sandbox
Content-Type: application/json
Date: Thu, 19 Sep 2024 00:18:27 GMT
Vary: Accept-Encoding
Via: 1.1 grafana
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Xss-Protection: 1; mode=block
```

`grafana/otel-lgtm:0.7.3` uses tempo `v2.6.0`

```
HTTP/1.1 200 OK
Content-Length: 752
Content-Security-Policy: sandbox
Content-Type: 
Date: Thu, 19 Sep 2024 00:20:30 GMT
Vary: Accept-Encoding
Via: 1.1 grafana
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Xss-Protection: 1; mode=block
```

The issue still happens in version `grafana/otel-lgtm:0.7.4`

**To Reproduce**
1. Start Tempo 2.5.0
2. Write a trace
3. Read trace

**Expected behavior**
Response should include header `Content-Type: application/json`

**Environment:**
[grafana/otel-lgtm](https://github.com/grafana/docker-otel-lgtm/)

**Additional Context**
I'm using [RestAssured](https://rest-assured.io/) to perform jsonpath operations but due to the lack of the header tests started failing when docker image version was updated.

### PR DESCRIPTION
**Pull request by javiermolinar**
**What this PR does**:
This pr brings back the `application-json ` content-type header.
Previously the common combiner harcoded the header to application json. Now we need to initialize the combiner with default values

**Which issue(s) this PR fixes**:
Fixes #4121

**Checklist**
- [x] Tests updated
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: modules/frontend/combiner/metrics_query_range.go [hunk 1]
```diff
@@ -60,6 +61,7 @@ func NewTypedQueryRange(req *tempopb.QueryRangeRequest, trackDiffs bool) (GRPCCo
 		return nil, err
 	}
 
+	initHTTPCombiner(c.(*genericCombiner[*tempopb.QueryRangeResponse]), api.HeaderAcceptJSON)
```
Comment (joe-elliott) [inline modules/frontend/combiner/metrics_query_range.go:64]: is there a reason not to do this in the `NewQueryRange` func above? 

same Q for all below.

Comment (javiermolinar) [reply modules/frontend/combiner/metrics_query_range.go]: Right I got confused with the typed methods

**Review by joe-elliott — APPROVED** [review]
