### PR TITLE
Fix incorrectly reported vulture errors

### LINKED ISSUE #2792: Vulture incorrectly reports failures since r107
**Describe the bug**
Since installing r107 the vulture is reporting errors for trace not found and incorrect results. After rolling back to the r106 vulture the errors went away. This strongly suggests that the data is fine and some change in vulture/the http client caused the issue:

image

Fix the vulture!

### PR DESCRIPTION
**Pull request by stoewer**
Fix vulture problems:
* Since #2649 the function `RandomAttrFromTrace()` may return attributes with resource scope. This caused several problems in vulture:
  * When searching for `service.name` the matching traces can exceed the limit and the relevant trace could be missing from the result
    *Solution: skip the `service.name` attribute when selecting random attributes*
  * Vulture's `searchTraceql()` function was only searching through span attributes
    *Solution: change query template from `span.%s="%s"` to `.%s="%s"`*
  
* The order of attributes in generated data can differ from the order of attributes in traces retrieved from the API.
  *Solution: sort attributes before testing traces for equality*

**Which issue(s) this PR fixes**:
Fixes #2792

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: pkg/util/trace_info.go [hunk 1]
```diff
@@ -265,8 +265,13 @@ func RandomAttrFromTrace(t *tempopb.Trace) *v1common.KeyValue {
 
 	// maybe choose resource attribute
 	res := batch.Resource
-	if len(res.Attributes) > 0 && rand.Int()%2 == 1 {
-		return randFrom(r, res.Attributes)
+	if len(res.Attributes) > 0 && r.Int()%2 == 1 {
+		attr := randFrom(r, res.Attributes)
+		// skip service.name because service names have low cardinality and produce queries with
+		// too many results in tempo-vulture
+		if attr.Key != "service.name" {
```
Comment (mapno) [inline pkg/util/trace_info.go:272]: Should we also skip other attributes such as `namespace`, `cluster`?

**Review by joe-elliott — APPROVED** [review]
I'm good on this, but do what change caused vulture to start failing?

**Comment by stoewer** [comment]
> but do what change caused vulture to start failing?

The vulture problems were introduced by #2649. Before vulture was only testing span attributes. Since dedicated attribute columns are supported on resource and span scope, the test data was changed such that it also includes a resource attributes. This caused all the problems mentioned in the PR description
