### PR TITLE
Configure S3's credential chain based on config

### LINKED ISSUE #2888: 2.2.2 regression: S3 storage does not work with AWS IRSA authentication anymore
**Describe the bug**
After upgrading Tempo from `2.2.1`to `2.2.2` our Tempo instances could no longer access S3. We use AWS IRSA [^1] to provide AWS credentials.

The regression seems to be introduced by https://github.com/grafana/tempo/pull/2871
My current **guess** is the AWS SDK now prefers the EC2 instance role over IRSA.

**To Reproduce**
1. Deploy Tempo 2.2.1 on AWS EKS with S3 storage and IRSA authentication
2. Tempo should start and be able to access S3 as expected
3. Upgrade Tempo to 2.2.2 
4. Tempo should now crash during startup with S3 permission errors

**Expected behavior**
Tempo should continue to use the AWS IRSA provided credentials.

**Environment:**
 - Infrastructure: Kubernetes (AWS EKS)
 - Deployment tool: Helm (tempo-distributed - 1.6.3 - upgraded from 1.6.2)

**Additional Context**
Service logs (compactor):
```
level=info ts=2023-09-04T09:01:59.662782222Z caller=main.go:221 msg="initialising OpenTracing tracer"
level=info ts=2023-09-04T09:01:59.680278556Z caller=main.go:108 msg="Starting Tempo" version="(version=2.2.2, branch=HEAD, revision=5e18d78ba)"
level=error ts=2023-09-04T09:01:59.728222984Z caller=main.go:111 msg="error running Tempo" err="failed to init module services error initialising module: store: failed to create store unexpected error from ListObjects on <bucket_name>: Access Denied"
```

AWS environment variables in a running container:
```
$ env | grep -i aws
AWS_ROLE_ARN=arn:aws:iam::XXXXXXXXXXX:role/eks-development-v2-tempo
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token
AWS_STS_REGIONAL_ENDPOINTS=regional
AWS_DEFAULT_REGION=eu-central-1
AWS_REGION=eu-central-1
```

Storage configuration (copied from `tempo-distributed` Helm values):
```yaml
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::XXXXXXXXXXX:role/eks-development-v2-tempo"

    storage:
      trace:
        backend: s3
        s3:
          bucket: <bucket_name>
          endpoint: s3.eu-central-1.amazonaws.com
          region: eu-central-1 # Added during troubleshooting
```

[^1]: https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html

### PR DESCRIPTION
**Pull request by mapno**
**What this PR does**:

Configures the S3 credentials chain based on what S3 auth method is configured.

Added a config param to S3 config `native_aws_auth_enabled`. When enabled, Tempo will use the default authentication methods of the AWS SDK for go based on known environment variables and known AWS config files.

**Which issue(s) this PR fixes**:
Fixes #2888 

**Checklist**
- [ ] Tests updated
- [x] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: tempodb/backend/s3/config.go [hunk 1]
```diff
@@ -25,12 +25,13 @@ type Config struct {
...
-	Tags             map[string]string `yaml:"tags"`
-	StorageClass     string            `yaml:"storage_class"`
-	Metadata         map[string]string `yaml:"metadata"`
+	SignatureV2          bool              `yaml:"signature_v2"`
+	ForcePathStyle       bool              `yaml:"forcepathstyle"`
+	BucketLookupType     int               `yaml:"bucket_lookup_type"`
+	Tags                 map[string]string `yaml:"tags"`
+	StorageClass         string            `yaml:"storage_class"`
+	Metadata             map[string]string `yaml:"metadata"`
+	NativeAWSAuthEnabled bool              `yaml:"native_aws_auth_enabled"`
```
Comment (joe-elliott) [inline tempodb/backend/s3/config.go:34]: should we mimic the thanos config name? since that's probably what it's called in mimi/loki?

Comment (mapno) [reply tempodb/backend/s3/config.go:34]: I copied the name from [`mimir`](https://github.com/grafana/mimir/blob/main/pkg/storage/bucket/s3/config.go#L87). In `thanos-io/objstore` is called [`aws_sdk_auth`](https://github.com/thanos-io/objstore/blob/main/providers/s3/s3.go#L128). I don't have a preference.

Comment (joe-elliott) [reply tempodb/backend/s3/config.go:34]: Ah, didn't realize that this name came from Mimir. Good call :+1:

**Comment by mapno** [comment]
> @joe-elliott could we include some sort of documentation update alongside that tell what to configure for using this.

I've updated the docs to include the new config param. Does that cover your request?

**Review by joe-elliott — APPROVED** [review]
