### PR TITLE
Gogoproto coded etcd

### LINKED ISSUE #1213: panic: interface conversion: *v1.ExportTraceServiceRequest is not protoreflect.ProtoMessage: missing method ProtoReflect
**Describe the bug**
Tempo crashes when receiving OLTP telemetry

**To Reproduce**
1. Start Tempo via dockerhub image, "grafana/tempo:latest" at time of writing. `grafana/tempo@sha256:d6d1497d2b41ec74451dca762698c0321e3729b4bc83245f8b5c6360f481b625`
 ` tempo, version  (branch: main, revision: 045ede7f)`
Config:
```yaml
distributor:
  receivers:
    otlp:
      protocols:
        grpc:
```

2. Send some telemetry using Python library, using exact example provided on https://opentelemetry-python.readthedocs.io/en/stable/exporter/otlp/otlp.html
3. Tempo crashes:
```
panic: interface conversion: *v1.ExportTraceServiceRequest is not protoreflect.ProtoMessage: missing method ProtoReflect

goroutine 423 [running]:
github.com/grafana/tempo/pkg/gogocodec.(*gogoCodec).Unmarshal(0x1e89f00, {0xc000335800, 0x3c2, 0x3c2}, {0x212c5e0, 0xc000b1a300})
	/drone/src/pkg/gogocodec/gogocodec.go:65 +0xb3
google.golang.org/grpc.(*Server).processUnaryRPC.func2({0x212c5e0, 0xc000b1a300})
	/drone/src/vendor/google.golang.org/grpc/server.go:1263 +0x1f2
go.opentelemetry.io/collector/model/internal/data/protogen/collector/trace/v1._TraceService_Export_Handler({0x1e5f700, 0xc0009be740}, {0x27dc7c0, 0xc000b00a50}, 0xc0004d69c0, 0xc0009e60a0)
	/drone/src/vendor/go.opentelemetry.io/collector/model/internal/data/protogen/collector/trace/v1/trace_service.pb.go:206 +0x63
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0009fa000, {0x2809920, 0xc00017e600}, 0xc000532000, 0xc0009c09c0, 0x3af6660, 0x0)
	/drone/src/vendor/google.golang.org/grpc/server.go:1286 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc0009fa000, {0x2809920, 0xc00017e600}, 0xc000532000, 0x0)
	/drone/src/vendor/google.golang.org/grpc/server.go:1609 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/drone/src/vendor/google.golang.org/grpc/server.go:934 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/drone/src/vendor/google.golang.org/grpc/server.go:932 +0x294

```

**Expected behavior**
A: Tempo does not crash, even if the data provided is invalid. (I don't know enough about the opentelemetry-oython nor the wire protocol to tell if it is or not)
B: Tempo accepts the telemetry provided, assuming it was valid.

### PR DESCRIPTION
**Pull request by mapno**
**What this PR does**:

Registers etcd's server proto in gogoproto codec

**Which issue(s) this PR fixes**:
Fixes #1213 

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: pkg/gogocodec/gogocodec.go [hunk 1]
```diff
@@ -23,6 +23,7 @@ const (
 	jaegerProtoGenPkgPath = "github.com/jaegertracing/jaeger/proto-gen"
 	jaegerModelPkgPath    = "github.com/jaegertracing/jaeger/model"
 	otelProtoPkgPath      = "go.opentelemetry.io/collector"
+	etcdProtoPkgPath      = "go.etcd.io/etcd/api/v3/etcdserverpb"
```
Comment (joe-elliott) [inline pkg/gogocodec/gogocodec.go:26]: nice fix, but i'm wondering if we can just update our etcd dependency instead of adding it here?

does the most recent etcd support latest grpc/proto?

also, we will definitely need to cut a 1.3.1 with this. good catch.

File: example/docker-compose/distributed/docker-compose.yaml [hunk 2]
```diff
@@ -101,3 +101,40 @@ services:
       - GF_AUTH_DISABLE_LOGIN_FORM=true
     ports:
       - "3000:3000"
+
+  etcd1:
```
Comment (joe-elliott) [inline example/docker-compose/distributed/docker-compose.yaml:105]: this could be reduced to a single node etcd cluster for simplicity. not a big deal either way.

File: example/docker-compose/distributed/tempo-distributed.yaml [hunk 3]
```diff
@@ -25,14 +25,13 @@ ingester:
   lifecycler:
     ring:
       replication_factor: 3
-
-memberlist:
```
Comment (annanay25) [inline example/docker-compose/distributed/tempo-distributed.yaml:29]: Thanks for the fix @mapno. 

I'm wondering if we can add an e2e test here, it will be useful to protect against this in future PRs. Adding an example/docker-compose helps but adds a manual testing step.

Comment (mapno) [reply example/docker-compose/distributed/tempo-distributed.yaml]: Added the e2e test!

File: example/docker-compose/distributed/docker-compose.yaml (hunk 2 above)
Comment (mapno) [reply example/docker-compose/distributed/docker-compose.yaml]: Changed docker-compose for extending the e2e tests to use all options for the kv store.

File: pkg/gogocodec/gogocodec.go (hunk 1 above)
Comment (mapno) [reply pkg/gogocodec/gogocodec.go]: The gogocodec hack for etcd can be removed once it's upgraded to grpc >v1.38 is released (tentatively next release from v3.5.1). We're stuck with this for a bit I'm afraid.

Comment (mapno) [reply pkg/gogocodec/gogocodec.go]: FWIW, it's updated in [`main`](https://github.com/etcd-io/etcd/blob/main/api/go.mod#L11), but still unreleased

**Review by annanay25 — APPROVED** [review]
Nice work, LGTM! 🚀

File: integration/e2e/e2e_test.go [hunk 4]
```diff
@@ -131,130 +135,195 @@ func TestAllInOne(t *testing.T) {
...
-
-	tempoDistributor := util.NewTempoDistributor()
-	tempoQueryFrontend := util.NewTempoQueryFrontend()
-	tempoQuerier := util.NewTempoQuerier()
-	require.NoError(t, s.StartAndWaitReady(tempoIngester1, tempoIngester2, tempoIngester3, tempoDistributor, tempoQueryFrontend, tempoQuerier))
-
-	// wait for active ingesters
-	time.Sleep(1 * time.Second)
-	matchers := []*labels.Matcher{
+func TestMicroservicesWithKVStores(t *testing.T) {
```
Comment (joe-elliott) [inline integration/e2e/e2e_test.go:138]: fantastic addition :+1:
