### PR TITLE
Handle Partial Success in ConsumeTraces

### LINKED ISSUE #1957: Complete writing a batch even if some spans refused
**Describe the bug**
Currently if an ingester refuses traces b/c a trace is too large it will stop writing the current batch and return an error. The end result is that the first part of the batch was written but everything after the "trace too large" error is dropped. Let's continue writing the batch even if we receive a trace too large error.

Loop to write traces:
https://github.com/grafana/tempo/blob/909b487d4bac42797a786a10796664b4cfcd0746/modules/ingester/instance.go#L167

Trace too large returned here:
https://github.com/grafana/tempo/blob/909b487d4bac42797a786a10796664b4cfcd0746/modules/ingester/instance.go#L210

### PR DESCRIPTION
**Pull request by ie-pham**
**What this PR does**: 

1. Right now if a single trace in the batch triggers an error, Tempo drops the entire batch. This PR allows every trace in the batch to get a turn at getting pushed before returning a response to the client. 

2. From internal discussion, we are going to match what is required [here](https://github.com/open-telemetry/opentelemetry-proto/blob/main/docs/specification.md#partial-success-1) for partial success and return a `200` instead of an error. 

The tricky part was tallying up the discarded span count.

If replication factor is 3, then the minimum success is 2 (rep factor / 2 +1) and the max allowable error is 1. So initially I thought a simple logic should account for this. Tally up all the responses and if a trace is marked as "error" twice then we can consider that trace discarded. However, this approach is only doable if we were working with cases where the number of responses = replication factor. That is not the case. We think the ring.DoBatch function returns as soon as 2 errors or 2 successes are recorded without waiting for the third response (a partial success is still considered a success). In a perfect world where two those responses are exact the same, we would not have a problem. However, if we have a scenario where the lists of discarded traces are different in the two responses, it is hard to accurately determine whether a trace was discarded or not without the third response. 

Decision:
Since the discarded span count currently does not play an important role in the functionality of Tempo, I am going with the "over counting" solution. 

Since the number of responses is always the minimum success or more
```
	// max number of error allowed is {number of responses} - {minimum success required}
```
So if the replication factor is 3 and we get only 2 responses (and the minimum success required is 2), then the max number of error allowed is 0. If a trace is marked "error" even once, it will be considered discarded. However, for example, for replication of 5 with a minimum success of 3, if we only get 4 responses then with the same rules, the max error allowed is 1 not 0. 

This solution has drawbacks because we may overcount the number of discarded spans.  For example if we have one partial success and one total success, without the third response, there is a chance that whatever trace failed in the partial success actually was successfully processed in the third response but we will mark it as discarded. 

Another note is I am adding a mutex lock to collect the responses from the ingester. Will need to test this to make sure it does not impact performance too much. 

**Which issue(s) this PR fixes**:
Fixes #1957

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by ie-pham** [comment]
So the logic works but I'm just not sure if it's too convoluted to record the correct discarded span count by reason

File: modules/distributor/distributor.go [hunk 1]
```diff
@@ -378,11 +393,20 @@ func (d *Distributor) sendToIngestersViaBytes(ctx context.Context, userID string
...
 			SearchData: nil, // support for flatbuffer/v2 search has been removed. todo: cleanup the proto
+			SpanCounts: make([]tempopb.PreallocBytes, len(indexes)),
 		}
 
 		for i, j := range indexes {
 			req.Traces[i].Slice = marshalledTraces[j][0:]
 			req.Ids[i].Slice = traces[j].id
+
+			// convert span count int to byte : int => string => byte
+			spanCount, err := tempo_util.HexStringToTraceID(strconv.Itoa(traces[j].spanCount))
```
Comment (joe-elliott) [inline modules/distributor/distributor.go:404]: definitely shouldn't be going int -> string -> byte. that's a large performance penalty to go from int -> byte

File: pkg/tempopb/tempo.proto [hunk 2]
```diff
@@ -172,6 +172,8 @@ message PushBytesRequest {
   repeated bytes ids = 3 [(gogoproto.nullable) = false, (gogoproto.customtype) = "PreallocBytes"];
   // search data, length must match traces
   repeated bytes searchData = 4 [(gogoproto.nullable) = false, (gogoproto.customtype) = "PreallocBytes"];
+    // span count per trace
+  repeated bytes spanCounts = 5 [(gogoproto.nullable) = false, (gogoproto.customtype) = "PreallocBytes"];
```
Comment (joe-elliott) [inline pkg/tempopb/tempo.proto:176]: if span count is 1 byte then the max spans it can track is 2^8 which is likely not enough in a lot of scenarios. i question whether passing the span count at all is worth it tho.

File: modules/ingester/instance.go [hunk 3]
```diff
@@ -149,12 +166,66 @@ func newInstance(instanceID string, limiter *Limiter, writer tempodb.Writer, l *
...
+				internalErorCount += spanCount
+				if !strings.Contains(errors.Error(), err.Error()) {
+					errors.Add(err)
+				}
+			}
 		}
 	}
+
+	if len(errors) > 0 {
+		discardCountMessage := fmt.Sprintf(
```
Comment (joe-elliott) [inline modules/ingester/instance.go:218]: if we're going to pass back rich information like this we should just change the `PushResponse` method to have these fields.

**Review by joe-elliott — COMMENTED** [review]
I question the efforts to perfectly record dropped spans for each reason. I'm wondering if a better approach would be to change `PushResponse` to return trace indexes and rejection reasons back to the distributor. The distributor could then update the appropriate metrics based on the response.

File: modules/ingester/instance.go (hunk 3 above)
Comment (ie-pham) [reply modules/ingester/instance.go:218]: Yeah I originally had tried doing this but the response object never gets back to the distributor and I just assumed that was not possible. I will try to figure out what I did wrong there. Is there any additional things I need to do besides changing the protos for the response?

File: modules/distributor/distributor.go [hunk 4]
```diff
@@ -353,12 +360,12 @@ func (d *Distributor) PushTraces(ctx context.Context, traces ptrace.Traces) (*te
...
 }
 
-func (d *Distributor) sendToIngestersViaBytes(ctx context.Context, userID string, traces []*rebatchedTrace, keys []uint32) error {
-	// Marshal to bytes once
+func (d *Distributor) sendToIngestersViaBytes(ctx context.Context, userID string, traces []*rebatchedTrace, keys []uint32, totalSpanCount int, tracesByID map[uint32]*rebatchedTrace) error {
 	marshalledTraces := make([][]byte, len(traces))
 	for i, t := range traces {
 		b, err := d.traceEncoder.PrepareForWrite(t.trace, t.start, t.end)
 		if err != nil {
+			overrides.RecordDiscardedSpans(totalSpanCount, reasonInternalError, userID)
```
Comment (joe-elliott) [inline modules/distributor/distributor.go:368]: i think we should leave this outside `sendToIngesterViaBytes`. Basically either:

- `sendToIngesterViaBytes` returns an error meaning something unexpected happened and we can record drops due to internal errors.
- `sendToIngesterViaBytes` returns nil and internally it will record drops due to policy reasons.

i'm wondering if we want to completely stop recording internal error in metrics, and just rely on the error return. that would be for a future PR.

File: modules/distributor/distributor.go [hunk 5]
```diff
@@ -390,14 +401,51 @@ func (d *Distributor) sendToIngestersViaBytes(ctx context.Context, userID string
...
 		}
 
-		_, err = c.(tempopb.PusherClient).PushBytesV2(localCtx, &req)
+		response, err := c.(tempopb.PusherClient).PushBytesV2(localCtx, &req)
+		// response = nil, err = nil ==> entire batch processed successfully
+		// response = nil, err != nill ==> entire batch failed not related to livetraces or tracetoolong error
+		// response != nil, err = nil  ==>  at least one trace was discarded
 		metricIngesterAppends.WithLabelValues(ingester.Addr).Inc()
+
+		r.mu.Lock()
```
Comment (joe-elliott) [inline modules/distributor/distributor.go:410]: should we move this to the bottom? after checking response and err?

File: modules/distributor/distributor.go [hunk 6]
```diff
@@ -390,14 +401,51 @@ func (d *Distributor) sendToIngestersViaBytes(ctx context.Context, userID string
...
+	}
+
+	// count discarded span count
+	// due to the way that doBatch works, there is a possibility of overcounting discarded span count
+	// because we are not waiting for all responses to come back before returning
+	// but we predict a low frequency for that scenario
+	// todo: figure out a more accurate way to count discarded spans
+	r.mu.Lock()
+	maxLiveDiscardedCount, traceTooLargeDiscardedCount, internalErrorDiscardedCount := countDiscaredSpans(r.responses, tracesByID, d.ingestersRing.ReplicationFactor())
+	r.mu.Unlock()
```
Comment (joe-elliott) [inline modules/distributor/distributor.go:439]: deferring unlock is preferred when possible

File: modules/distributor/distributor.go [hunk 7]
```diff
@@ -515,23 +567,53 @@ func requestsByTraceID(batches []*v1.ResourceSpans, userID string, spanCount int
...
+	numResponses := len(responses)
+	quorum := (repFactor / 2) + 1 // min success required
+
+	// max number of error allowed is {number of responses} - {minimum success required}
+	// + 1 for error count that should mark a trace as discarded
+	maxError := (numResponses - quorum) + 1
+
+	// if a trace triggers two different errors in two different responses, the error that triggers the maxError count will be used
+	for _, response := range responses {
+		if response == nil {
```
Comment (joe-elliott) [inline modules/distributor/distributor.go:587]: i'm concerned about this error handling. if we get an error in DoBatch() above i'm fine with keeping it simple and just letting that error propagate all the way back just like it does now.

File: modules/ingester/ingester.go [hunk 8]
```diff
@@ -239,15 +239,18 @@ func (i *Ingester) PushBytesV2(ctx context.Context, req *tempopb.PushBytesReques
...
 	if err != nil {
+		level.Warn(log.Logger).Log(err.Error())
 		return nil, err
 	}
 
-	err = instance.PushBytesRequest(ctx, req)
-	if err != nil {
-		return nil, err
+	response, _ := instance.PushBytesRequest(ctx, req)
+	// distributor will determine if an error should be returned to the client
```
Comment (joe-elliott) [inline modules/ingester/ingester.go:247]: i think we should continue returning error. any unexpected error in the path should just make the whole thing 500. previously we treated drops due to limits as an error, but this PR changes that.

- everything works perfectly: 200/OK
- nothing fails, but we drop spans: 200/OK and tick up our metrics
- unexpected error: 500/INTERNAL

**Review by joe-elliott — COMMENTED** [review]
I have reviewed mainly the distributor part and I think we need to make some changes so I'm not quite going to dig deep on the ingester part yet.

Overall, this is really heading the right direction. A lot of comments and questions b/c this is a very performance sensitive part of the code and a very nuanced change.

Also, I think this invalidates: https://github.com/grafana/tempo/issues/1958 since we are just going to start returning 200 on dropped spans. Can you confirm?

File: pkg/tempopb/tempo.proto [hunk 9]
```diff
@@ -163,6 +163,12 @@ message Trace {
 message PushResponse {
 }
 
+message IngesterPushResponse {
+  repeated uint32 maxLiveErrorTraces = 1;
```
Comment (joe-elliott) [inline pkg/tempopb/tempo.proto:167]: we can just add these fields to the existing `PushResponse`. changing the response type will change the method signature which i think will break Tempo on rollout. 

speaking of, we will need to be thoughtful about what a rollout of this change will look like. we will need to nail down some more of the behavior as discussed in the comments first.

File: modules/distributor/distributor.go [hunk 10]
```diff
@@ -330,15 +338,14 @@ func (d *Distributor) PushTraces(ctx context.Context, traces ptrace.Traces) (*te
 			size)
 	}
 
-	keys, rebatchedTraces, err := requestsByTraceID(batches, userID, spanCount)
+	keys, rebatchedTraces, tracesByID, err := requestsByTraceID(batches, userID, spanCount)
```
[the remark this answers is not in the document]
Comment (ie-pham) [reply modules/distributor/distributor.go:341]: good call, fixed

File: modules/distributor/distributor.go (hunk 4 above)
Comment (ie-pham) [reply modules/distributor/distributor.go:368]: Have we ever used this for any debugging purposes?

Comment (joe-elliott) [reply modules/distributor/distributor.go:368]: Not that I'm aware of, but that metric is exposed to our cloud users so we would want to consider the impact before changing it.

File: CHANGELOG.md [hunk 11]
```diff
@@ -3,6 +3,8 @@
 * [FEATURE] New encoding vParquet3 with support for dedicated attribute columns (@mapno, @stoewer) [#2649](https://github.com/grafana/tempo/pull/2649)
 * [ENHANCEMENT] Assert ingestion rate limits as early as possible [#2640](https://github.com/grafana/tempo/pull/2703) (@mghildiy)
 
+* [CHANGE] **Breaking Change** Fix issue where tempo drops the entire batch if one trace triggers an error [#2571](https://github.com/grafana/tempo/pull/2571) (@ie-pham)
```
Comment (joe-elliott) [inline CHANGELOG.md:6]: Add details about why this is breaking. I believe it's b/c we are now returning 200/OK when we have partial success on write. A sentence about how this impacts the discarded spans metric would be good too.

File: modules/distributor/distributor.go [hunk 12]
```diff
@@ -141,6 +142,11 @@ type Distributor struct {
 	logger log.Logger
 }
 
+type PushByteRes struct {
```
Comment (joe-elliott) [inline modules/distributor/distributor.go:145]: except for bundling these two fields together there's not really a reason for this struct to exist. i would personally not create this for simplicity, but i'm not strongly opposed to it either

File: modules/distributor/distributor.go [hunk 13]
```diff
@@ -398,14 +407,36 @@ func (d *Distributor) sendToIngestersViaBytes(ctx context.Context, userID string
...
-		_, err = c.(tempopb.PusherClient).PushBytesV2(localCtx, &req)
+		response, err := c.(tempopb.PusherClient).PushBytesV2(localCtx, &req)
+		// response = {empty}, err = nil ==> entire batch processed successfully
+		// response = nil, err != nill ==> entire batch failed not related to livetraces or tracetoolong error
+		// response != {empty}, err = nil  ==>  at least one trace was discarded
 		metricIngesterAppends.WithLabelValues(ingester.Addr).Inc()
+
+		r.mu.Lock()
+		defer r.mu.Unlock()
+		r.responses = append(r.responses, response)
```
Comment (joe-elliott) [inline modules/distributor/distributor.go:418]: i think we should check for err != nil before the locking. if err != nil there's no reason to accumulate the responses.

File: modules/distributor/distributor.go [hunk 14]
```diff
@@ -526,20 +561,52 @@ func requestsByTraceID(batches []*v1.ResourceSpans, userID string, spanCount int
...
-func recordDiscaredSpans(err error, userID string, spanCount int) {
-	s := status.Convert(err)
-	if s == nil {
-		return
-	}
-	desc := s.Message()
+func countDiscaredSpans(responses []*tempopb.PushResponse, traces []*rebatchedTrace, repFactor int) (int, int, int) {
+	maxLiveDiscardedCount := 0
+	traceTooLargeDiscardedCount := 0
+	internalErrorDiscardedCount := 0
```
Comment (joe-elliott) [inline modules/distributor/distributor.go:567]: i don't think we need to count internal error here. `DoBatch()` will do the work of accounting for an error while sending to the ingesters.

i think we can drop the error handling/response == nil logic here and simplify.

File: modules/ingester/instance.go [hunk 15]
```diff
@@ -154,14 +170,50 @@ func newInstance(instanceID string, limiter *Limiter, overrides ingesterOverride
...
 	for j := range req.Traces {
+		index := int32(j)
+
 		err := i.PushBytes(ctx, req.Ids[j].Slice, req.Traces[j].Slice)
 		if err != nil {
-			return err
+			errorMessage := err.Error()
+			totalTracesDiscarded++
+
+			if strings.Contains(errorMessage, overrides.ErrorPrefixLiveTracesExceeded) {
```
Comment (joe-elliott) [inline modules/ingester/instance.go:188]: we can compare the errors directly. We no longer need to do string comparisons.

File: modules/ingester/instance.go [hunk 16]
```diff
@@ -154,13 +172,49 @@ func newInstance(instanceID string, limiter *Limiter, overrides ingesterOverride
...
 	for j := range req.Traces {
+		index := int32(j)
+
 		err := i.PushBytes(ctx, req.Ids[j].Slice, req.Traces[j].Slice)
 		if err != nil {
-			return err
+			errorMessage := err.Error()
+			totalTracesDiscarded++
+
+			if _, ok := err.(*maxLiveTracesError); ok {
```
Comment (joe-elliott) [inline modules/ingester/instance.go:190]: let's use `errors.Is()`. it will handle error wrapping and is the canonical method of detecting error equality in go

File: modules/ingester/instance.go [hunk 17]
```diff
@@ -154,13 +172,49 @@ func newInstance(instanceID string, limiter *Limiter, overrides ingesterOverride
 	return i, nil
 }
 
-func (i *instance) PushBytesRequest(ctx context.Context, req *tempopb.PushBytesRequest) error {
+func (i *instance) PushBytesRequest(ctx context.Context, req *tempopb.PushBytesRequest) *tempopb.PushResponse {
+	var errors util.MultiError
+
+	maxLiveErrorTraces := make([]int32, 0)
```
Comment (joe-elliott) [inline modules/ingester/instance.go:178]: the compiler likely does this for us, but we should not call `make()` here so the slices are only allocated if an error occurs

File: modules/ingester/instance.go [hunk 18]
```diff
@@ -154,13 +172,49 @@ func newInstance(instanceID string, limiter *Limiter, overrides ingesterOverride
...
 		if err != nil {
-			return err
+			errorMessage := err.Error()
+			totalTracesDiscarded++
+
+			if _, ok := err.(*maxLiveTracesError); ok {
+				maxLiveErrorTraces = append(maxLiveErrorTraces, index)
+				// only log one of each occurrence
+				if !strings.Contains(errorMessage, overrides.ErrorPrefixLiveTracesExceeded) {
+					errors.Add(err)
```
Comment (joe-elliott) [inline modules/ingester/instance.go:194]: how about we just log these at a warn level?

File: modules/ingester/instance.go [hunk 19]
```diff
@@ -154,13 +172,49 @@ func newInstance(instanceID string, limiter *Limiter, overrides ingesterOverride
...
+			}
 		}
 	}
+
+	// at least one failure
+	if totalTracesDiscarded > 0 {
+		return &tempopb.PushResponse{
+			MaxLiveErrorTraces:       maxLiveErrorTraces,
+			TraceTooLargeErrorTraces: traceTooLargeErrorTraces,
+			Error:                    errors.Error(),
```
Comment (joe-elliott) [inline modules/ingester/instance.go:213]: is there any reason to return the error to the ingester?

File: modules/ingester/instance.go [hunk 20]
```diff
@@ -154,13 +172,49 @@ func newInstance(instanceID string, limiter *Limiter, overrides ingesterOverride
...
+		}
+	}
+
+	// no failure
```
Comment (joe-elliott) [inline modules/ingester/instance.go:217]: to reduce complexity it might make more sense to always return a value `tempopb.PushResponse`. even if there are no errors. in this case the slices will just be empty.

**Review by joe-elliott — COMMENTED** [review]
heading the right direction

File: modules/ingester/instance.go (hunk 19 above)
Comment (ie-pham) [reply modules/ingester/instance.go:213]: I was thinking that we might want to eventually return this error message once we start implementing OTEL `export` call with the partial success error. Should we just leave it out until we implement it?

Comment (joe-elliott) [reply modules/ingester/instance.go:213]: yeah, leave it out for now. i think it tightens the design.

File: modules/distributor/distributor.go [hunk 21]
```diff
@@ -398,15 +401,39 @@ func (d *Distributor) sendToIngestersViaBytes(ctx context.Context, userID string
 			return err
 		}
 
-		_, err = c.(tempopb.PusherClient).PushBytesV2(localCtx, &req)
+		response, err := c.(tempopb.PusherClient).PushBytesV2(localCtx, &req)
+		// response = {empty}, err = nil ==> entire batch processed successfully
+		// response = nil, err != nill ==> entire batch failed not related to livetraces or tracetoolong error
+		// response != {empty}, err = nil  ==>  at least one trace was discarded
```
Comment (kvrhdn) [inline modules/distributor/distributor.go:407]: I feel like this would be easier to read as follows:

```suggestion
		response, err := c.(tempopb.PusherClient).PushBytesV2(localCtx, &req)
		metricIngesterAppends.WithLabelValues(ingester.Addr).Inc()

		if err != nil {
			// internal error, abandon the entire batch
			metricIngesterAppendFailures.WithLabelValues(ingester.Addr).Inc()
			return err
		}
		
		// batch was (partially) accepted, gather responses and we are done

		return nil
```

File: modules/distributor/distributor.go [hunk 22]
```diff
@@ -398,15 +401,39 @@ func (d *Distributor) sendToIngestersViaBytes(ctx context.Context, userID string
...
 		metricIngesterAppends.WithLabelValues(ingester.Addr).Inc()
-		if err != nil {
+
+		if response != nil {
+			mu.Lock()
+			defer mu.Unlock()
+			responses = append(responses, response)
 			metricIngesterAppendFailures.WithLabelValues(ingester.Addr).Inc()
 		}
```
Comment (kvrhdn) [inline modules/distributor/distributor.go:415]: The `metricIngesterAppendFailures.WithLabelValues(ingester.Addr).Inc()` in here is wrong, this is the branch for successful push requests right?

File: modules/distributor/distributor.go [hunk 23]
```diff
@@ -526,20 +557,39 @@ func requestsByTraceID(batches []*v1.ResourceSpans, userID string, spanCount int
...
 
-func recordDiscaredSpans(err error, userID string, spanCount int) {
-	s := status.Convert(err)
-	if s == nil {
-		return
-	}
-	desc := s.Message()
+func countDiscaredSpans(responses []*tempopb.PushResponse, traces []*rebatchedTrace, repFactor int) (int, int) {
+	maxLiveDiscardedCount := 0
+	traceTooLargeDiscardedCount := 0
```
Comment (kvrhdn) [inline modules/distributor/distributor.go:562]: Nit: you can used named return values, makes the method more explicit + you don't need to initialise these

```suggestion
func countDiscaredSpans(responses []*tempopb.PushResponse, traces []*rebatchedTrace, repFactor int) (maxLiveDiscardedCount int, traceTooLargeDiscardedCount int) {
```

The line gets a bit long though... 🤔

**Review by kvrhdn — COMMENTED** [review]
Still looking through instance.go and the e2e test but already going to release some comments 🙂

File: modules/distributor/distributor.go (hunk 21 above)
Comment (ie-pham) [reply modules/distributor/distributor.go:407]: ohh i like this

File: modules/distributor/distributor.go [hunk 24]
```diff
@@ -397,15 +400,37 @@ func (d *Distributor) sendToIngestersViaBytes(ctx context.Context, userID string
...
-		return err
+
+		mu.Lock()
+		defer mu.Unlock()
+		responses = append(responses, response)
+		return nil
 	}, func() {})
+	// if err != nil, we discarded everything because of an internal error
+	if err != nil {
+		return err
```
Comment (joe-elliott) [inline modules/distributor/distributor.go:418]: nit: it might be clearer at this point to move:
```
overrides.RecordDiscardedSpans(spanCount, reasonInternalError, userID)
```
in here since all discarded span counts are recorded right here.

File: modules/distributor/distributor.go [hunk 25]
```diff
@@ -376,6 +376,9 @@ func (d *Distributor) sendToIngestersViaBytes(ctx context.Context, userID string
 		op = ring.Write
 	}
 
+	responses := make([]*tempopb.PushResponse, 0, d.ingestersRing.ReplicationFactor())
```
Comment (joe-elliott) [inline modules/distributor/distributor.go:379]: won't this be the count of all ingesters? one response for each ingester? not sure how easy it is to get that number.

File: modules/distributor/distributor.go [hunk 26]
```diff
@@ -525,20 +554,40 @@ func requestsByTraceID(batches []*v1.ResourceSpans, userID string, spanCount int
...
+	maxError := (numResponses - quorum) + 1
+
+	// if a trace triggers two different errors in two different responses, the error that triggers the maxError count will be used
+	for _, response := range responses {
+		if response == nil { // no errors
+			continue
+		}
+		for _, traceIndex := range response.MaxLiveErrorTraces {
+			traceIndex := int(traceIndex)
+			discardedTraces[traceIndex]++
```
Comment (joe-elliott) [inline modules/distributor/distributor.go:573]: need safeguard here. it would be too easy for a bug to panic the distributors

File: modules/distributor/distributor.go [hunk 27]
```diff
@@ -525,20 +554,40 @@ func requestsByTraceID(batches []*v1.ResourceSpans, userID string, spanCount int
...
 
-	if strings.HasPrefix(desc, overrides.ErrorPrefixLiveTracesExceeded) {
-		overrides.RecordDiscardedSpans(spanCount, reasonLiveTracesExceeded, userID)
-	} else if strings.HasPrefix(desc, overrides.ErrorPrefixTraceTooLarge) {
-		overrides.RecordDiscardedSpans(spanCount, reasonTraceTooLarge, userID)
-	} else {
-		overrides.RecordDiscardedSpans(spanCount, reasonInternalError, userID)
+	// max number of error allowed is {number of responses} - {minimum success required}
+	// + 1 for error count that should mark a trace as discarded
+	maxError := (numResponses - quorum) + 1
```
Comment (joe-elliott) [inline modules/distributor/distributor.go:564]: i may be misunderstanding but i don't think this is true. i think there's one response for each ingester, but each trace will actually only be written to 3 (in the case of RF3). I think max error is:
```
maxError = (repFactor / 2) // integer division
```
the reason max error is below true quorum is b/c we don't require 1 write per batch to complete before this logic hits and for safety we consider it a failure.

File: modules/distributor/distributor.go [hunk 28]
```diff
@@ -525,20 +554,40 @@ func requestsByTraceID(batches []*v1.ResourceSpans, userID string, spanCount int
...
+			discardedTraces[traceIndex]++
+			if discardedTraces[traceIndex] == maxError {
+				spanCount := traces[traceIndex].spanCount
+				maxLiveDiscardedCount += spanCount
+			}
+		}
+
+		for _, traceIndex := range response.TraceTooLargeErrorTraces {
+			traceIndex := int(traceIndex)
+			discardedTraces[traceIndex]++
```
Comment (joe-elliott) [inline modules/distributor/distributor.go:582]: same as above

File: modules/ingester/instance.go [hunk 29]
```diff
@@ -15,7 +16,7 @@ import (
 	"github.com/gogo/status"
 	"github.com/google/uuid"
 	"github.com/opentracing/opentracing-go"
-	"github.com/pkg/errors"
+	pkgErrors "github.com/pkg/errors"
```
Comment (joe-elliott) [inline modules/ingester/instance.go:19]: any particular reason we're adding this? .New, .Wrap, and .Wrapf all appear in the standard `errors` package

**Review by joe-elliott — COMMENTED** [review]
getting down to the nitty gritty. Have a few comments, let me know what you think.

This change is close!

File: modules/ingester/instance.go (hunk 29 above)
Comment (ie-pham) [reply modules/ingester/instance.go:19]: That was already there. When i imported the standard `errors` package, I had to rename that particular `errors` package. But I could also just not import the standard package and just use what's already there, which is that `pkg/errors`.

Comment (joe-elliott) [reply modules/ingester/instance.go:19]: oh, i see. it would be my inclination to just move everything to `errors`

**Comment by ie-pham** [comment]
So... I refactored

Before we would collect all the responses and then loop through the responses to count the number of times a specific trace has errored to determine whether it was truly discarded or not. 

Now:

We will have
```go
batchResults := make([][]int, len(keys))
```
where the outer lay represents the traces and the inner represents the responses from `ingester.PushBytesV2()` collected for each trace. The responses will be represented by 0, 1, 2 where 0=success, 1=maxlivetraces, 2=tracetoolarge

At the end we will iterate through batchResults and any trace that do not have the minimum required successes (the minimum required 0s) will be marked as discarded.

File: modules/distributor/distributor.go [hunk 30]
```diff
@@ -397,15 +405,54 @@ func (d *Distributor) sendToIngestersViaBytes(ctx context.Context, userID string
...
+		if err != nil { // internal error, drop entire batch
 			metricIngesterAppendFailures.WithLabelValues(ingester.Addr).Inc()
+			return err
 		}
-		return err
+
+		// assign a number for each index that had an error
+		// maxLive = 1, traceTooLarge = 2
+		// indexes that do not have an error will have a default 0 value
+		ringBatchResults := make([]int, len(indexes))
```
Comment (joe-elliott) [inline modules/distributor/distributor.go:419]: i'm fine with something simpler. we don't need to perfectly count all reasons failed, right?  for instance in RF3 if a trace is rejected once for max live and once for too large then there is no "right answer" for how to metric dropped spans. all we really need to know is total errors as well as one (the first?) of the rejection reasons.

File: modules/distributor/distributor.go [hunk 31]
```diff
@@ -397,15 +405,54 @@ func (d *Distributor) sendToIngestersViaBytes(ctx context.Context, userID string
...
+		for _, value := range response.MaxLiveErrorTraces {
+			ringBatchResults[value] = maxLiveTracesErrInt
+		}
+		for _, value := range response.TraceTooLargeErrorTraces {
+			ringBatchResults[value] = traceTooLargeErrorInt
```
Comment (joe-elliott) [inline modules/distributor/distributor.go:424]: probably should double check the value before indexing into the slice.

File: modules/distributor/distributor.go (hunk 30 above)
Comment (joe-elliott) [reply modules/distributor/distributor.go:419]: allocating this for every push might get costly. can't we translate the response data directly into the batchResults from the response using the indexes?

File: modules/distributor/distributor.go [hunk 32]
```diff
@@ -376,6 +378,12 @@ func (d *Distributor) sendToIngestersViaBytes(ctx context.Context, userID string
 		op = ring.Write
 	}
 
+	batchResults := make([][]int, len(keys))
```
Comment (joe-elliott) [inline modules/distributor/distributor.go:381]: this is tough. for each trace we need to know 2 things to accurately count refused spans:

- number of successes
- first (or last or any) reported error

it's possible there is an optimization to be made here to only track these fields instead of every returned value for each trace. we'd need to do some benchmarking to determine if there was a better path. possibly something to keep in mind while we finish up.

File: modules/ingester/instance.go [hunk 33]
```diff
@@ -154,14 +152,28 @@ func newInstance(instanceID string, limiter *Limiter, overrides ingesterOverride
...
-func (i *instance) PushBytesRequest(ctx context.Context, req *tempopb.PushBytesRequest) error {
+func (i *instance) PushBytesRequest(ctx context.Context, req *tempopb.PushBytesRequest) *tempopb.PushResponse {
+	pr := &tempopb.PushResponse{}
+
 	for j := range req.Traces {
+
 		err := i.PushBytes(ctx, req.Ids[j].Slice, req.Traces[j].Slice)
 		if err != nil {
-			return err
+			if errors.Is(err, errMaxLiveTraces) {
```
[the remark this answers is not in the document]
Comment (ie-pham) [reply modules/ingester/instance.go:162]: it is using `errMaxLiveTraces/errMaxLiveTraces`

the functions newMaxLiveTracesError/newMaxLiveTracesError just add a step to print a warning log

```go
var (
	errTraceTooLarge = errors.New(overrides.ErrorPrefixTraceTooLarge)
	errMaxLiveTraces = errors.New(overrides.ErrorPrefixLiveTracesExceeded)
)

func newTraceTooLargeError(traceID common.ID, instanceID string, maxBytes, reqSize int) error {
	level.Warn(log.Logger).Log("msg", fmt.Sprintf("%s: max size of trace (%d) exceeded while adding %d bytes to trace %s for tenant %s",
		overrides.ErrorPrefixTraceTooLarge, maxBytes, reqSize, hex.EncodeToString(traceID), instanceID))
	return errTraceTooLarge
}
```

File: modules/ingester/instance.go [hunk 34]
```diff
@@ -34,34 +35,31 @@ import (
...
 
 // Errors returned on Query.
 var (
-	ErrTraceMissing = errors.New("Trace missing")
+	ErrTraceMissing = pkgErrors.New("Trace missing")
 )
 
 const (
-	traceDataType = "trace"
+	traceDataType         = "trace"
```
[the remark this answers is not in the document]
Comment (ie-pham) [reply modules/ingester/instance.go:60]: apparently here
```
	// measure received bytes as sum of slice lengths
	// type byte is guaranteed to be 1 byte in size
	// ref: https://golang.org/ref/spec#Size_and_alignment_guarantees
	i.bytesReceivedTotal.WithLabelValues(i.instanceID, traceDataType).Add(float64(len(traceBytes)))
```

File: modules/ingester/instance.go [hunk 35]
```diff
@@ -34,34 +35,31 @@ import (
...
-		overrides.ErrorPrefixTraceTooLarge, e.maxBytes, e.reqSize, hex.EncodeToString(e.traceID), e.instanceID)
+func newMaxLiveTracesError(instanceID string, limit string) error {
+	level.Warn(log.Logger).Log("msg", fmt.Sprintf("%s max live traces exceeded for tenant %s: %v", overrides.ErrorPrefixLiveTracesExceeded, instanceID, limit))
+	return errMaxLiveTraces
 }
 
 // Errors returned on Query.
 var (
-	ErrTraceMissing = errors.New("Trace missing")
+	ErrTraceMissing = pkgErrors.New("Trace missing")
```
[the remark this answers is not in the document]
Comment (ie-pham) [reply modules/ingester/instance.go:56]: apparently it is not used anywhere, I'll get rid of it

File: modules/distributor/distributor.go (hunk 32 above)
Comment (ie-pham) [reply modules/distributor/distributor.go:381]: the only optimization I can think of which I don't know if it will be an optimization is:

```go

// instead of batchResults
NumSuccessByTraceIndex   = make([]int, len(keys)
LastPushErrorByTraceIndex = make([]int, len(keys)
```

And every time we get a PushResponse, we update each trace accordingly. What do you think?

File: modules/frontend/v1/frontendv1pb/frontend.pb.go
[the remark this answers is not in the document]
Comment (ie-pham) [reply modules/frontend/v1/frontendv1pb/frontend.pb.go:1]: i probably just need to rebase and gen-proto again 👍

**Comment by jcmackie** [comment]
Hiya @joe-elliott et al.

We are pretty keen to see this merged into Tempo.
As you can probably imagine we have many traces that hit our size limit, and it's nice to be able to set that limit and protect our Tempo deployment from ridiculously sized traces.

But if we are also losing lots of spans for traces that are otherwise okay. We've tuned down our batch size to reduce the blast radius but it only helps so much.

If we feel confident that all the trace data that should get into Tempo can do so successfully, that will go a long way towards our confidence in the reliability of this tool.

Please let us know if there's any way we can help.

File: modules/ingester/instance.go [hunk 36]
```diff
@@ -154,14 +144,39 @@ func newInstance(instanceID string, limiter *Limiter, overrides ingesterOverride
...
+	atLeastOneError := false
+	pr := &tempopb.PushResponse{}
+
 	for j := range req.Traces {
+
 		err := i.PushBytes(ctx, req.Ids[j].Slice, req.Traces[j].Slice)
 		if err != nil {
-			return err
+			// only make list if there is at least one error
+			if !atLeastOneError {
```
Comment (joe-elliott) [inline modules/ingester/instance.go:156]: let's make this block a function for clarity. we can also test it directly which is nice b/c it does some weird things.

something like:
```
  addTraceError([]tempopb.PushErrorReason, pos int, err error) []tempopb.PushErrorReason
```

File: modules/ingester/instance.go [hunk 37]
```diff
@@ -154,14 +144,39 @@ func newInstance(instanceID string, limiter *Limiter, overrides ingesterOverride
...
+			}
+			if errors.Is(err, errMaxLiveTraces) {
+				pr.ErrorsByTrace = append(pr.ErrorsByTrace, tempopb.PushErrorReason_MAX_LIVE_TRACES)
+				continue
+			}
+
+			if errors.Is(err, errTraceTooLarge) {
+				pr.ErrorsByTrace = append(pr.ErrorsByTrace, tempopb.PushErrorReason_TRACE_TOO_LARGE)
+				continue
+			}
```
Comment (joe-elliott) [inline modules/ingester/instance.go:173]: if error is neither max live traces or trace too large do we just swallow it here? should we return other errors?

File: modules/distributor/distributor.go [hunk 38]
```diff
@@ -530,19 +561,54 @@ func requestsByTraceID(batches []*v1.ResourceSpans, userID string, spanCount int
...
-	desc := s.Message()
 
-	if strings.HasPrefix(desc, overrides.ErrorPrefixLiveTracesExceeded) {
-		overrides.RecordDiscardedSpans(spanCount, reasonLiveTracesExceeded, userID)
-	} else if strings.HasPrefix(desc, overrides.ErrorPrefixTraceTooLarge) {
-		overrides.RecordDiscardedSpans(spanCount, reasonTraceTooLarge, userID)
+	return maxLiveDiscardedCount, traceTooLargeDiscardedCount
+}
+
+func (d *Distributor) processPushResponse(pushResponse *tempopb.PushResponse, numSuccessByTraceIndex []int, lastErrorReasonByTraceIndex []tempopb.PushErrorReason, numOfTraces int, indexes []int) {
```
Comment (joe-elliott) [inline modules/distributor/distributor.go:583]: this function needs some cleanup and tests. going to make some stylistic suggestions.

File: modules/distributor/distributor.go [hunk 39]
```diff
@@ -530,19 +561,54 @@ func requestsByTraceID(batches []*v1.ResourceSpans, userID string, spanCount int
...
+	// no errors
+	if len(pushResponse.ErrorsByTrace) == 0 {
+		for _, reqBatchIndex := range indexes {
+			if reqBatchIndex < numOfTraces {
```
Comment (joe-elliott) [inline modules/distributor/distributor.go:587]: i prefer writing this like. it reduces nesting and makes it easier to read. 

```
<for loop> {
  if <thing is bad> {
    <log my error>
    continue
  }
  
  <do happy path things>
}
```

File: modules/distributor/distributor.go [hunk 40]
```diff
@@ -530,19 +561,54 @@ func requestsByTraceID(batches []*v1.ResourceSpans, userID string, spanCount int
...
+				currentNumSuccess := numSuccessByTraceIndex[reqBatchIndex]
+				numSuccessByTraceIndex[reqBatchIndex] = currentNumSuccess + 1
```
Comment (joe-elliott) [inline modules/distributor/distributor.go:589]: i think this can be simplified to:
```
numSuccessByTraceIndex[reqBatchIndex]++
```

File: modules/distributor/distributor.go [hunk 41]
```diff
@@ -530,19 +561,54 @@ func requestsByTraceID(batches []*v1.ResourceSpans, userID string, spanCount int
...
+			} else {
+				level.Warn(d.logger).Log("msg", fmt.Sprintf("batch index %d out of bound for length %d", reqBatchIndex, numOfTraces))
+			}
+		}
 	} else {
-		overrides.RecordDiscardedSpans(spanCount, reasonInternalError, userID)
+		for ringIndex, pushError := range pushResponse.ErrorsByTrace {
```
Comment (joe-elliott) [inline modules/distributor/distributor.go:595]: similar to above you can actually remove two levels of nesting here.

File: modules/distributor/distributor.go [hunk 42]
```diff
@@ -530,19 +561,54 @@ func requestsByTraceID(batches []*v1.ResourceSpans, userID string, spanCount int
...
-func recordDiscaredSpans(err error, userID string, spanCount int) {
-	s := status.Convert(err)
-	if s == nil {
-		return
+func countDiscaredSpans(numSuccessByTraceIndex []int, lastErrorReasonByTraceIndex []tempopb.PushErrorReason, traces []*rebatchedTrace, repFactor int) (maxLiveDiscardedCount int, traceTooLargeDiscardedCount int) {
+	quorum := int(math.Floor(float64(repFactor)/2)) + 1 // min success required
+
+	for traceIndex, numSuccess := range numSuccessByTraceIndex {
+		// we will count anything that did not receive min success as discarded
+		if numSuccess < quorum {
```
Comment (joe-elliott) [inline modules/distributor/distributor.go:569]: loop nesting can be reduced. see below.

**Review by joe-elliott — COMMENTED** [review]
some stylistic comments. almost there!

File: modules/overrides/config.go [hunk 43]
```diff
@@ -30,9 +30,9 @@ const (
 	GlobalIngestionRateStrategy = "global"
 
 	// ErrorPrefixLiveTracesExceeded is used to flag batches from the ingester that were rejected b/c they had too many traces
-	ErrorPrefixLiveTracesExceeded = "LIVE_TRACES_EXCEEDED:"
+	ErrorPrefixLiveTracesExceeded = "LIVE_TRACES_EXCEEDED"
```
[the remark this answers is not in the document]
Comment (ie-pham) [reply modules/overrides/config.go:33]: the fmt.Print was different but will change to make everything match

**Review by joe-elliott — APPROVED** [review]
Nice addition!

**Comment by adugar-conga** [comment]
In which release version of Grafana Tempo will this be addressed ?

**Comment by adugar-conga** [comment]
@joe-elliott  @ie-pham In which release version of Grafana Tempo will this be addressed ?

**Comment by joe-elliott** [comment]
This feature is merged into main and will be in the next release of Tempo. We attempt a 3 month cadence on OSS releases but make no guarantees.

Releases are listed here: https://github.com/grafana/tempo/releases/
