### PR TITLE
Frontend Refactor

### LINKED ISSUE #1392: Query limits don't work or work unexpectedly
**Describe the bug**
Query limits don't work or work unexpectedly  

**To Reproduce**
Make a query in grafana with tempo datasource with limit parameter, for example 1000. Looking at query inspector in response object there is an array with more than 1000 elements.
Also max_result_limit not respected. 

query frontend settings:
```
query_frontend:
  max_outstanding_per_tenant: 2000
  search:
    default_result_limit: 100
    max_result_limit: 1500
    concurrent_jobs: 300
    max_duration: 168h
```

Tested on tempo-querier traces with the same time range of 2 days:

with limit set to 1000 (less than max_result_limit)

Снимок экрана 2022-04-18 в 13 12 17

with limit greater than max_result_limit

Снимок экрана 2022-04-18 в 13 16 28

Same issue when querying via search api.
Is this behavior expected or am I missing some settings for this limits?

**Expected behavior**
When limit is set greater than max_result_limit response objects count is equal to max_result_limit.

**Environment:**
 - Infrastructure: Kubernetes, Grafana (v8.4.4)
 - Deployment tool: helm

**Additional Context**

### PR DESCRIPTION
**Pull request by joe-elliott**
**What this PR does**:
Refactors the frontend pipeline to accomplish a number of goals detailed below. Currently only the search pipelines have been moved over to the new structure. There will be follow up PRs for other endpoints.

Goals:
- Provide streaming on all query endpoints
- Consolidate recombination logic in the frontend/combiner package
- Consolidate all pipeline building logic in the frontend/pipeline package

See the [readme in the pipeline package](https://github.com/grafana/tempo/pull/3400/files#diff-3c5207b6a5e79bfb1b84334ee056b7cd262e6017abc2a316692f2778c84e6662) for details.

**Which issue(s) this PR fixes**:
Fixes #1392

This PR is progress toward https://github.com/grafana/tempo/issues/3366 with an eventual goal to close it.

**Changes**
- removes `tempo_query_frontend_multitenant`... metrics b/c they don't quite fit into the current pattern. this can be improved later. 

**todo**:
- [x] Flesh out readme.md in /pipeline to describe how to build new pipeline elements

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by joe-elliott** [comment]
> @joe-elliott Was there doc added? I didn't see any in the file list to review.

There was not. This change is invisible to the user. Unchecking the docs item!

File: modules/frontend/pipeline/pipeline.go [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+// Wrap implements Middleware.
+func (f MiddlewareFunc) Wrap(w http.RoundTripper) http.RoundTripper {
+	return f(w)
+}
+
+//
+// Builder and Bridge
+//
+
+// MergeMiddlewares takes a set of ordered middlewares and merges them into a pipeline
```
Comment (mdisibio) [inline modules/frontend/pipeline/pipeline.go:62]: nit: comment

File: modules/frontend/pipeline/async_sharding.go [hunk 2]
```diff
@@ -0,0 +1,104 @@
...
+	go func() {
+		defer asyncResp.done()
+
+		reqIdx := 0
+		for {
+			req := reqFn(reqIdx)
+			reqIdx++
+
+			// else check for a request to pass down the pipeline
+			if req == nil {
```
Comment (mdisibio) [inline modules/frontend/pipeline/async_sharding.go:37]: What do you think about the caller passing the expected number of requests?  It looks like the only reference is for multi-tenant where the number is known.

File: modules/frontend/pipeline/async_sharding.go [hunk 3]
```diff
@@ -0,0 +1,104 @@
...
+		}
+
+		wg.Wait()
+	}()
+
+	return asyncResp
+}
+
+// NewAsyncSharderLimitedGoroutines creates a new AsyncResponse that shards requests to the next AsyncRoundTripper[*http.Response] using a limited number of goroutines.
+func NewAsyncSharderLimitedGoroutines(concurrent int, reqs <-chan *http.Request, resps Responses[*http.Response], next AsyncRoundTripper[*http.Response]) Responses[*http.Response] {
```
Comment (mdisibio) [inline modules/frontend/pipeline/async_sharding.go:62]: These two methods would be clearer to me if they were renamed to `NewAsyncSharderFunc` and `NewAsyncSharderChan`.  That looks like the main difference (in this current version at least). Since they both have concurrently limits.

File: modules/frontend/combiner/common.go [hunk 4]
```diff
@@ -1,74 +1,104 @@
...
-	code          int
-	statusMessage string
-	err           error
+	//
+	httpStatusCode int
+	httpRespBody   string
 }
 
-func (c *genericCombiner[R]) AddRequest(res *http.Response, _ string) error {
+// AddRequest actually adds a response. Rename?
```
Comment (mdisibio) [inline modules/frontend/combiner/common.go:37]: Yes please 👍

File: modules/frontend/frontend.go [hunk 5]
```diff
@@ -55,19 +56,19 @@ func New(cfg Config, next http.RoundTripper, o overrides.Interface, reader tempo
...
 
 	// inject multi-tenant middleware in multi-tenant routes
 	traceByIDMiddleware := MergeMiddlewares(
 		newMultiTenantMiddleware(cfg, combiner.NewTraceByID, logger),
 		newTraceByIDMiddleware(cfg, o, logger), retryWare)
 
-	searchMiddleware := MergeMiddlewares(
-		newMultiTenantMiddleware(cfg, combiner.NewSearch, logger),
-		newSearchMiddleware(cfg, o, reader, searchCache, logger), retryWare)
+	searchPipeline := pipeline.Build(
```
Comment (mdisibio) [inline modules/frontend/frontend.go:68]: Double checking my understanding:  Search is the only API moved to the new pipeline?

File: modules/frontend/frontend.go [hunk 6]
```diff
@@ -55,19 +56,19 @@ func New(cfg Config, next http.RoundTripper, o overrides.Interface, reader tempo
...
+		asyncPipeline(cfg, newAsyncSearchSharder(reader, o, cfg.Search.Sharder, logger), logger),
```
Comment (mdisibio) [inline modules/frontend/frontend.go:69]: This kind of hides the multi-tenant handling.  Is there a way to "flatten" it up to this level like the other apis are built?

File: modules/frontend/frontend.go [hunk 7]
```diff
@@ -265,12 +253,26 @@ func buildUpstreamRequestURI(originalURI string, params url.Values) string {
...
 
-		return RoundTripperFunc(func(r *http.Request) (*http.Response, error) {
+		return pipeline.RoundTripperFunc(func(r *http.Request) (*http.Response, error) {
 			return searchRT.RoundTrip(r)
 		})
 	})
 }
+
+func asyncPipeline(cfg Config, sharder pipeline.AsyncMiddleware[*http.Response], logger log.Logger) []pipeline.AsyncMiddleware[*http.Response] {
+	if cfg.MultiTenantQueriesEnabled {
```
Comment (mdisibio) [inline modules/frontend/frontend.go:267]: I think this might be changing multi-tenant behavior unintentionally.  Previously when `cfg.MultiTenantQueriesEnabled==false` it would pass-through to next().  But now it looks like it will fail whenever multiple tenant IDs are given.   

For example if `cfg.MultiTenantQueriesEnabled==false` and `X-Scope-OrgID: foo|bar` it will fail instead of using tenantID `foo|bar` literally?

File: modules/frontend/frontend.go (hunk 6 above)
Comment (joe-elliott) [reply modules/frontend/frontend.go]: good call. it's nice to see all the pipeline components in one spot. changed to:
```
	searchPipeline := pipeline.Build(
		[]pipeline.AsyncMiddleware[*http.Response]{
			multiTenantMiddleware(cfg, logger),
			newAsyncSearchSharder(reader, o, cfg.Search.Sharder, logger),
		},
		[]pipeline.Middleware{cacheWare, statusCodeWare, retryWare},
		next)
```

File: modules/frontend/frontend.go (hunk 7 above)
Comment (joe-elliott) [reply modules/frontend/frontend.go:270]: yup, you are correct. fixed to return a "no-op" middleware when `MultiTenantQueriesEnabled==false`. this will cause the pipeline to treat `foo|bar` literally.

File: modules/frontend/pipeline/collector_grpc.go [hunk 8]
```diff
@@ -0,0 +1,146 @@
...
+	if err != nil {
+		return grpcError(err)
+	}
+
+	// stores any error that occurs during the streaming
+	//  the wg protects the store from concurrent writes/reads
+	var overallErr error
+
+	wg := &sync.WaitGroup{}
+	wg.Add(1)
```
[the remark this answers is not in the document]
Comment (joe-elliott) [reply modules/frontend/pipeline/collector_grpc.go:47]: good catch! removed.

File: modules/frontend/pipeline/async_sharding.go (hunk 3 above)
Comment (joe-elliott) [reply modules/frontend/pipeline/async_sharding.go:62]: The intention was for `NewAsyncSharder` to create one goroutine for every concurrrent downstream request. This is the way the current frontend works.

`NewAsyncSharderLimitedGoroutines` creates a limited number of goroutine "workers" that can then fire up to concurrency requests downstream.

I don't think this is working the way I intended it to. This was the last area of code I was looking at closely. I'm going to do some more experimentation but I think that we will still need one goroutine per request. Perhaps we eventually migrate to an async request pipeline as well as response?

Comment (joe-elliott) [reply modules/frontend/pipeline/async_sharding.go:62]: Ok, I've cleaned these up and used your suggested names. I like where they are now, but think there's room for improvement.

File: modules/frontend/pipeline/async_sharding.go [hunk 9]
```diff
@@ -0,0 +1,104 @@
...
+
+				asyncResp.Send(resp)
+				concurrencyLimiter.Done()
+			}
+		}()
+	}
+
+	go func() {
+		if resps != nil {
+			asyncResp.Send(resps)
```
[the remark this answers is not in the document]
Comment (mdisibio) [reply modules/frontend/pipeline/async_sharding.go:96]: Got it, thanks.   Caching is another instance, where the cacheKey is passed through the context.

File: modules/frontend/pipeline/sync_handler_cache.go [hunk 10]
```diff
@@ -0,0 +1,165 @@
...
+
+	if len(buffer) == 0 {
+		return
+	}
+
+	c.c.Store(ctx, []string{key}, [][]byte{buffer})
+}
+
+// fetch fetches the response body from the cache. the caller assumes the responsibility of closing the response body.
+func (c *frontendCache) fetch(key string, pb proto.Message) bool {
```
Comment (mdisibio) [inline modules/frontend/pipeline/sync_handler_cache.go:131]: This method looks unused except for the test, and wasn't sure about json+proto.Message.  Since we know it's a `proto.Message` we could store the binary representation in cache instead.

**Review by mdisibio — APPROVED** [review]
I really like this, the async parts seem clearer and streaming everywhere will be awesome.  Definitely think we can make the sync parts (cache, etc) also async in the future.

File: modules/frontend/pipeline/sync_handler_cache.go (hunk 10 above)
Comment (joe-elliott) [reply modules/frontend/pipeline/sync_handler_cache.go:131]: yup. i do think there's an opportunity to make the sync part of the pipeline type aware with generics which would allow this, but we're not quite there yet
