### PR TITLE
Fix flush during shutdown

### LINKED ISSUE #3298: Ingester does not flush on call /shutdown or flush_all_on_shutdown
**Describe the bug**
Ingester fails to flush its data when the /shutdown endpoint is called:

```
level=info ts=2024-01-16T14:03:36.661581721Z caller=flush.go:92 msg="shutdown handler called"
level=info ts=2024-01-16T14:03:36.661641905Z caller=lifecycler.go:533 msg="lifecycler loop() exited gracefully" ring=ingester
level=info ts=2024-01-16T14:03:36.661670623Z caller=lifecycler.go:907 msg="changing instance state from" old_state=ACTIVE new_state=LEAVING ring=ingester
level=info ts=2024-01-16T14:03:36.661769772Z caller=lifecycler.go:978 msg="transfers are disabled"
level=info ts=2024-01-16T14:03:36.661801813Z caller=lifecycler.go:995 msg="lifecycler entering final sleep before shutdown" final_sleep=0s
level=info ts=2024-01-16T14:03:36.661851741Z caller=lifecycler.go:585 msg="instance removed from the KV store" ring=ingester
level=info ts=2024-01-16T14:03:36.66251607Z caller=flush.go:177 msg="head block cut. enqueueing flush op" userid=single-tenant block=c9734a5a-1069-43b3-a2a7-9877b6a4f775
level=info ts=2024-01-16T14:03:36.662632056Z caller=flush.go:240 org_id=single-tenant msg="Abandoning op in flush queue because ingester is shutting down" op=0 block=c9734a5a-1069-43b3-a2a7-9877b6a4f775 attempts=1
level=info ts=2024-01-16T14:03:36.662731329Z caller=module_service.go:114 msg="module stopped" module=ingester
level=info ts=2024-01-16T14:03:36.662730418Z caller=flush.go:106 msg="shutdown handler complete"
```

Similar issue happens if `flush_all_on_shutdown` is true and the pod is deleted

**To Reproduce**
1. Start Tempo 2.3.0
2. Send some traces
3. Call the /shutdown endpoint

**Expected behavior**
I expect the block to be flushed to the backend storage, instead of abandoning the operation

**Environment:**
 Deployed to EKS using helm, tempo-distributed version 1.7.3

**Additional Context**
I have found [issue 2609](https://github.com/grafana/tempo/issues/2609) which is basically for the same topic. There is a statement there that after setting up persistent volumes `flush_all_on_shutdown` was working as expected. I suspect that this was because when using persistent volumes, the pod will flush the remaining data to the backend storage **after it has been restarted**. To verify this I set up the backend s3 with a prefix: 

```
  storage:
    trace:
      backend: s3
      s3:
        bucket: ...
        region: us-east-1
        endpoint: s3.us-east-1.amazonaws.com
        prefix: tempo-test1
```

Sent some test traces to the ingesters, then updated prefix to `tempo-test2` and redeployed. The missing data was flushed to s3, but to the new prefix, meaning the flush happened after restart. 

The linked issue also discusses some code paths, and how `i.flushRemaining()` should block until everything is flushed. However the issue is that the codepath from `i.flushRemaining()` -> `i.sweepAllInstances()` -> `i.sweepInstance()` -> `i.enqueue()` results in executing a goroutine, which allows the code in `i.flushRemaining()` to return and `i.flushQueues.Stop()` to be called before the goroutine continues. 

A possible fix would be to execute the actual `i.flushQueues.Enqueue()` synchronously instead of in a goroutine if no jitter was requested: 

```
func (i *Ingester) enqueue(op *flushOp, jitter bool) {
	delay := time.Duration(0)

	if jitter {
		delay = time.Duration(rand.Float32() * float32(flushJitter))
	}

	op.at = time.Now().Add(delay)

	go func() {
		time.Sleep(delay)

		// Check if shutdown initiated
		if i.flushQueues.IsStopped() {
			handleAbandonedOp(op)
			return
		}

		err := i.flushQueues.Enqueue(op)
		if err != nil {
			handleFailedOp(op, err)
		}
	}()
}
```

### PR DESCRIPTION
**Pull request by madaraszg-tulip**
**What this PR does**:
This PR fixes flush during shutdown. Previously the flush code hit an asynchronous goroutine resulting in abandoning the flush op. 

**Which issue(s) this PR fixes**:
Fixes #3298 

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by madaraszg-tulip** [comment]
Ran this locally, the logs show successful flush during shutdown:

```
level=info ts=2024-01-17T16:31:26.712711089Z caller=flush.go:92 msg="shutdown handler called"
level=info ts=2024-01-17T16:31:26.712758983Z caller=lifecycler.go:533 msg="lifecycler loop() exited gracefully" ring=ingester
level=info ts=2024-01-17T16:31:26.712798868Z caller=lifecycler.go:907 msg="changing instance state from" old_state=ACTIVE new_state=LEAVING ring=ingester
level=info ts=2024-01-17T16:31:26.712908808Z caller=lifecycler.go:978 msg="transfers are disabled"
level=info ts=2024-01-17T16:31:26.712947118Z caller=lifecycler.go:995 msg="lifecycler entering final sleep before shutdown" final_sleep=0s
level=info ts=2024-01-17T16:31:26.713005317Z caller=lifecycler.go:585 msg="instance removed from the KV store" ring=ingester
level=info ts=2024-01-17T16:31:26.713811692Z caller=flush.go:177 msg="head block cut. enqueueing flush op" userid=single-tenant block=8c267ea6-d2fd-4731-bdbb-639603199abd
level=info ts=2024-01-17T16:31:26.71388407Z caller=flush.go:253 msg="completing block" userid=single-tenant blockID=8c267ea6-d2fd-4731-bdbb-639603199abd
level=info ts=2024-01-17T16:31:26.720550211Z caller=flush.go:260 msg="block completed" userid=single-tenant blockID=8c267ea6-d2fd-4731-bdbb-639603199abd duration=6.672139ms
level=info ts=2024-01-17T16:31:26.720744525Z caller=flush.go:309 msg="flushing block" userid=single-tenant block=8c267ea6-d2fd-4731-bdbb-639603199abd
level=info ts=2024-01-17T16:31:27.016457154Z caller=flush.go:106 msg="shutdown handler complete"
level=info ts=2024-01-17T16:31:27.016458565Z caller=module_service.go:120 msg="module stopped" module=ingester
```

File: modules/ingester/flush.go [hunk 1]
```diff
@@ -349,20 +362,15 @@ func (i *Ingester) enqueue(op *flushOp, jitter bool) {
...
-			handleAbandonedOp(op)
-			return
-		}
-
-		err := i.flushQueues.Enqueue(op)
-		if err != nil {
-			handleFailedOp(op, err)
-		}
-	}()
+	if jitter {
```
Comment (joe-elliott) [inline modules/ingester/flush.go:365]: stylistic nit: i would have started the method with:
```
if !jitter {
  i.enqueueExec(op)
  return
}

<rest of func can assume jitter = true>
```

i think it would be clearer, but not wrong the way you've written it

**Review by joe-elliott — COMMENTED** [review]
this is looking good, but we'll need you to sign the CLA before merging

**Comment by joe-elliott** [comment]
Seeing a lot failures on flushes in the integration tests. This change seems to have negatively impacted that logic somehow.

**Comment by madaraszg-tulip** [comment]
I ran the integration test locally, and it finished successfully, so I'm not sure how to address this.

**Comment by madaraszg-tulip** [comment]
I finally had some failures when running integration tests locally for the third time. Looks like intermittent errors triggered by timing. Will see if I can dig up something.

**Comment by madaraszg-tulip** [comment]
Can we move forward with this PR? I think I've demonstrated that the test failures that we've seen are present in the main branch, and not introduced by my changes.

**Review by joe-elliott — APPROVED** [review]
Apologies for the delay, I'm good on this fix.

The only issue is that currently CLA assistant is not unblocking the PR.

**Comment by joe-elliott** [comment]
I followed the instructions here:

https://github.com/cla-assistant/cla-assistant/blob/main/COMMON_ISSUES.md#cla-assistant-status-or-comment-not-updated-1

and it unblocked it! Nice!

Thanks for the contribution.
