### PR TITLE
Fix Ingesters Occassionally Double Flushing

### LINKED ISSUE #217: Ingesters sometimes fail to flush
Ingesters sometimes fail to flush with this message:
```
msg="failed to flush user" err="remove /var/tempo/wal/b0c58d18-03d5-4f25-b24a-3359886d0c8d:1: no such file or directory"
```

This is innocuous in that it means that the wal file was already cleared, but should still be investigated.

### PR DESCRIPTION
**Pull request by joe-elliott**
**What this PR does**:
Occassionally ingesters fail to flush due to a double queuing (#217) issue discovered by @calvernaz.  This PR looks to fix that by:

- Creating a shim in front of the priority queues `ExclusiveQueues` that prevents multiple items from being queued with the same key
- Adjusting the `flushLoop()` to either call `.Requeue()` or `.ClearKey()` after flush has failed or succeeded
- Consolidated helper methods to extract prometheus metric values to `./pkg/util/test`
- Actually wait for flush queues to clear in `stopping()` eep!

**Which issue(s) this PR fixes**:
Fixes #217 

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: pkg/flushqueues/exclusivequeues.go [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+
+// Dequeue removes the next op from the requested queue.  After dequeueing the calling
+//  process either needs to call ClearKey or Requeue
+func (f *ExclusiveQueues) Dequeue(q int) util.Op {
+	return f.queues[q].Dequeue()
+}
+
+// Requeue adds an op that is presumed to already be covered by activeKeys
+func (f *ExclusiveQueues) Requeue(op util.Op) {
+	f.index++
```
Comment (mdisibio) [inline pkg/flushqueues/exclusivequeues.go:48]: Might not matter, but should this be atomic?

Comment (joe-elliott) [reply pkg/flushqueues/exclusivequeues.go:48]: Yeah, there is a race condition here.  I think just hashing op.Key() and modding it might be an easier choice.

File: pkg/flushqueues/exclusivequeues.go [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+	flushQueueIndex := f.index % len(f.queues)
+	f.queues[flushQueueIndex].Enqueue(op)
+}
+
+// ClearKey unblocks the requested key.  This should be called only after a flush has been successful
+func (f *ExclusiveQueues) ClearKey(key string) {
```
Comment (mdisibio) [inline pkg/flushqueues/exclusivequeues.go:54]: Thoughts on the signature of this being `Clear(op util.Op)` to match other funcs?

**Review by mdisibio — APPROVED** [review]
lgtm.  A few minor comments mentioned, but more of just questions than recommendations.

File: pkg/flushqueues/exclusivequeues.go (hunk 1 above)
Comment (joe-elliott) [reply pkg/flushqueues/exclusivequeues.go]: Decided against hashing the key b/c right now it's just the tenant id.  This means in a single tenant high volume environment every single operation would hit the same queue.  Made it an atomic int instead.

File: pkg/flushqueues/exclusivequeues.go [hunk 3]
```diff
@@ -0,0 +1,64 @@
...
+
+// Requeue adds an op that is presumed to already be covered by activeKeys
+func (f *ExclusiveQueues) Requeue(op util.Op) {
+	flushQueueIndex := int(f.index.Inc()) % len(f.queues)
+	f.queues[flushQueueIndex].Enqueue(op)
+}
+
+// ClearKey unblocks the requested key.  This should be called only after a flush has been successful
+func (f *ExclusiveQueues) Clear(op util.Op) {
+	f.activeKeys.Delete(op.Key())
```
Comment (calvernaz) [inline pkg/flushqueues/exclusivequeues.go:56]: Wondering if we should delete the key on dequeue - there is no risk of double queueing because `enqueue` is protecting it. However, it would allow re-queueing in case it fails - is my understanding that with the clear happening after, the re-queueing will be a `noop` because the key still active.

**Review by calvernaz — COMMENTED** [review]
LGTM, I just have a question regarding the clear operation.

File: pkg/flushqueues/exclusivequeues.go (hunk 3 above)
Comment (joe-elliott) [reply pkg/flushqueues/exclusivequeues.go:56]: I think we do need to leave the key during dequeue.  After calling `Dequeue()` the calling code needs to either call `Requeue()` if there was a failure or `Clear()` if it succeeded.  Otherwise we could get a double queue during the period in which we are flushing.

The structure looks like this:
```
		op := i.flushQueues.Dequeue(j)

		err := i.flushUserTraces(op.userID)
		if err != nil {
			i.flushQueues.Requeue(op)
			continue
		}

		i.flushQueues.Clear(op)
```

Comment (calvernaz) [reply pkg/flushqueues/exclusivequeues.go:56]: Yeah I saw that - so if it fails the requeue won't add the `opflush` because the key is still there.
```
	_, ok := f.activeKeys.Load(op.Key())
	if ok {
		return
	}
```

And because of the code above - no requeue is possible if the key already there.

Comment (joe-elliott) [reply pkg/flushqueues/exclusivequeues.go:56]: `Requeue()` doesn't check the map.  Only `Enqueue()` does.  `Requeue()` is designed to be used if you fail to handle the operation.  `Enqueue()` is used by the code generating the initial ops.

**Review by annanay25 — APPROVED** [review]

File: pkg/flushqueues/exclusivequeues.go (hunk 3 above)
Comment (calvernaz) [reply pkg/flushqueues/exclusivequeues.go:56]: I was being confused by the name `Enqueue` that wraps the actual queue. Thanks for clarifying.
