### PR TITLE
Parquet fixes

### LINKED ISSUE #1541: Parquet Storage Panic
**Describe the bug**
We have been using parquet for a week but suddenly it's crashed and whenever i try open it it's crashed again. I've removed tempo data folder to make it work. The disk was not full.

**Environment:**
 - Infrastructure: Ubuntu 22
 - Deployment tool: Compiling branch main(08a4995030c72869fea9a4b67928ad0b2eff8675) to binary.

**Additional Context**
`"failed to pushToQueue traces to tenant single-tenant queue: queue is full"

panic: runtime error: index out of range [0] with length 0

goroutine 368 [running]:
github.com/grafana/tempo/tempodb/encoding/vparquet.traceToParquet(0xc066004480?)
        /root/tempo/repo/tempo/tempodb/encoding/vparquet/schema.go:171 +0x1a2c
github.com/grafana/tempo/tempodb/encoding/vparquet.CreateBlock({0x2493e38, 0xc0000500b0}, 0xc000a34690, 0xc00cbedb88?, {0x2486670, 0xc0c4ff7140}, {0x2494420, 0x3524180}, {0x249ffc0, 0xc000d08160}, ...)
        /root/tempo/repo/tempo/tempodb/encoding/vparquet/create.go:58 +0x1f2
github.com/grafana/tempo/tempodb/encoding/vparquet.Encoding.CreateBlock(...)
        /root/tempo/repo/tempo/tempodb/encoding/vparquet/encoding.go:32
github.com/grafana/tempo/tempodb.(*readerWriter).CompleteBlockWithBackend(0xc000357140, {0x2493e38, 0xc0000500b0}, 0xc031d908c0, {0x2483220, 0x3524830}, {0x249ffc0, 0xc000d08160}, {0x249bfe0, 0xc000d08170})
        /root/tempo/repo/tempo/tempodb/tempodb.go:240 +0x396
github.com/grafana/tempo/modules/ingester.(*instance).CompleteBlock(0xc00037b560, {0x12, 0x2f, 0xa3, 0x13, 0xa0, 0xb1, 0x45, 0xbf, 0xb7, ...})
        /root/tempo/repo/tempo/modules/ingester/instance.go:294 +0x163
github.com/grafana/tempo/modules/ingester.(*Ingester).handleComplete(0xc000b38f00, 0xc0a27bc7d0)
        /root/tempo/repo/tempo/modules/ingester/flush.go:250 +0x25f
github.com/grafana/tempo/modules/ingester.(*Ingester).flushLoop(0xc000b38f00, 0x7)
        /root/tempo/repo/tempo/modules/ingester/flush.go:203 +0xc7
created by github.com/grafana/tempo/modules/ingester.New
        /root/tempo/repo/tempo/modules/ingester/ingester.go:89 +0x1f0`

### PR DESCRIPTION
**Pull request by mdisibio**
**What this PR does**:
This PR fixes a few issues with parquet and some lint:
* Multiblock iterator was losing last item from each prefetch iterator since it didn't check for io.EOF
* Multiblock iterator was combining unnecessarily
* Panic when translation from proto if first span was missing
* Was writing "\<root span not yet received>\" to the data file
* Vendor update for upstream fix
* Parameterizes `tempodb/TestCompactionRoundtrip` to run against every encoding (how several of these issues were surfaced)

**Which issue(s) this PR fixes**:
Fixes #1541 

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by joe-elliott** [comment]
Let's go!

File: tempodb/encoding/vparquet/create.go [hunk 1]
```diff
@@ -38,7 +38,7 @@ func CreateBlock(ctx context.Context, cfg *common.BlockConfig, meta *backend.Blo
 	s := newStreamingBlock(ctx, cfg, meta, r, to, tempo_io.NewBufferedWriter)
 
 	for {
-		_, obj, err := i.Next(ctx)
+		id, obj, err := i.Next(ctx)
```
Comment (joe-elliott) [inline tempodb/encoding/vparquet/create.go:41]: this iterator is just exposing slices over an internal buffer. if id is held onto longer than this loop we should make a copy.

**Review by joe-elliott — APPROVED** [review]

File: tempodb/encoding/vparquet/create.go (hunk 1 above)
Comment (mdisibio) [reply tempodb/encoding/vparquet/create.go:41]: Good catch. It looks like it's actually ok since inside the iterator is using fresh byte slices in [UnmarshalObjectFromReader](https://github.com/grafana/tempo/blob/main/tempodb/encoding/v2/object.go#L64), but this is also unnecessarily hanging onto the object body.  Will fix.
