### PR TITLE
Exemplars UX improvements

### LINKED ISSUE #4632: Query exemplars field not respected
**Describe the bug**
When running a TraceQL metrics query with exemplars enabled, the `exemplars` query field value is not respected by Tempo, it always returns the amount of exemplars decided internally in Tempo. 

**To Reproduce**
1. Start Tempo (2.7.0)
2. Run a metrics query `{} | rate()` and set the exemplars field as `3`, for example

**Expected behavior**
In the example above I would expect to only receive 3 exemplars, but receive more.

### LINKED ISSUE #4856: TraceQL Metrics exemplar distribution is skewed
**Describe the bug**
Exemplars from TraceQL metrics are not homogeneously distributed across the series but instead cluster towards the right/left side, leading to potential biases in analysis.

Exemplars sometimes appear on the left side and other times on the right, meaning the sampling decision directly impacts their distribution

Image

Showing all the series:

Image

**To Reproduce**

1. Run a TraceQL metrics query that returns many series with exemplars
2. Check the exemplars distribution

**Expected behavior**
Exemplars are distributed homogeneously

### PR DESCRIPTION
**Pull request by ruslan-mikhailov**
**What this PR does**:

1. Distribute exemplars over time.
a. Change the approach to calculating requested exemplars from frontend to querier. Instead of equal share, calculate it based on block time range. The biggest block will receive more exemplars than a small block
b. Change sampling algorithm by fixing number of sampling buckets

Before the change:
image

After the change:
image

**Results:**
Before:
Pasted image 20250523145320

After:
Pasted image 20250523144347

2. Hard limit returned exemplars from query-frontend during final aggregation.

**Which issue(s) this PR fixes**:
Fixes #4856
Fixes #4632

**Checklist**

- [x] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: modules/frontend/metrics_query_range_sharder.go [hunk 1]
```diff
@@ -228,8 +263,8 @@ func (s *queryRangeSharder) buildBackendRequests(ctx context.Context, tenantID s
 	queryHash := hashForQueryRangeRequest(&searchReq)
 	colsToJSON := api.NewDedicatedColumnsToJSON()
 
-	exemplarsPerBlock := s.exemplarsPerShard(uint32(len(metas)), searchReq.Exemplars)
-	for _, m := range metas {
+	exemplarsPerBlock := s.exemplarsPerShard(metas, searchReq.Exemplars)
```
Comment (mdisibio) [inline modules/frontend/metrics_query_range_sharder.go:266]: Should we also scale the number of exemplars for generatorRequest based on the time range?  I think it sends over the whole limit, which was also a reason exemplars seemed to clump in recent data.

**Comment by knylander-grafana** [comment]
@ruslan-mikhailov  Do we need to update the docs so people understand the changes you've made in this PR? Maybe this doc? https://grafana.com/docs/tempo/latest/traceql/metrics-queries/#exemplars

File: integration/e2e/api/query_range_test.go [hunk 2]
```diff
@@ -64,34 +64,67 @@ sendLoop:
...
+			"{} | count_over_time() by (status)",
+			"{status != error} | count_over_time() by (status)",
+		} {
+			t.Run(fmt.Sprintf("%s: %s", exeplarsCase.name, query), func(t *testing.T) {
+				queryRangeRes := callQueryRange(t, tempo.Endpoint(tempoPort), query, exeplarsCase.exemplars, debugMode)
+				require.NotNil(t, queryRangeRes)
+				require.GreaterOrEqual(t, len(queryRangeRes.GetSeries()), 1)
+				if query == "{} | quantile_over_time(duration, .5, 0.9, 0.99)" {
+					t.Skip("Bug in quantile_over_time in calculating exemplars")
+				}
```
Comment (ruslan-mikhailov) [inline integration/e2e/api/query_range_test.go:113]: This is not https://github.com/grafana/tempo/pull/5145 , it's another issue. I need to create a bug and add it in code as a comment

Comment (ruslan-mikhailov) [reply integration/e2e/api/query_range_test.go:113]: https://github.com/grafana/tempo/issues/5167

File: integration/e2e/limits_test.go [hunk 3]
```diff
@@ -239,6 +239,9 @@ func TestQueryLimits(t *testing.T) {
 
 	require.Eventually(t, func() bool {
 		_, err = client.QueryTrace(tempoUtil.TraceIDToHexString(traceID[:]))
+		if err == nil {
+			return false
+		}
```
Comment (mapno) [inline integration/e2e/limits_test.go:244]: Is this correct? The trace might not be immediately too big because it's sent in batches.

File: modules/frontend/metrics_query_range_sharder.go (hunk 1 above)
Comment (ruslan-mikhailov) [reply modules/frontend/metrics_query_range_sharder.go:293]: Good point! With bucket fix, it still should distribute fairly, but by cutting the exemplars parameter, we can reduce the load to generators.

I pushed exemplar splitting between generator and querier in a separate commit. Could you please take a look?

**Review by mapno — APPROVED** [review]
LGTM

**Comment by ruslan-mikhailov** [comment]
\+ rebase from latest main

**Comment by ruslan-mikhailov** [comment]
\+ linter fixes

File: integration/e2e/api/query_range_test.go (hunk 2 above)
Comment (ruslan-mikhailov) [reply integration/e2e/api/query_range_test.go]: \+
