### PR TITLE
Patch WAL dedupe when search is disabled

### LINKED ISSUE #967: Index out of range at `completing block` log message
**Describe the bug**

It appears that when a block is completing, we have an `index out of range` panic.

```
level=info ts=2021-09-17T15:08:48.719429979Z caller=compactor.go:104 msg="enabling compaction"
level=info ts=2021-09-17T15:08:48.719564092Z caller=tempodb.go:368 msg="compaction and retention enabled."
level=info ts=2021-09-17T15:09:50.54346294Z caller=frontend.go:109 tenant=single-tenant method=GET traceID=49c4f409f3d3da11 url=/api/traces/5cfd75829f7636034774f39fd6294859 duration=58.658035ms response_size=12225 status=200
level=info ts=2021-09-17T15:10:20.505573808Z caller=frontend.go:109 tenant=single-tenant method=GET traceID=34b75bfdabe97a08 url=/api/traces/2640357a799d655265fe5791c5734dbb duration=23.859058ms response_size=7949 status=200
level=info ts=2021-09-17T15:10:50.522667639Z caller=frontend.go:109 tenant=single-tenant method=GET traceID=528a543f686516df url=/api/traces/0c360f4ee129bece3f5a3fab9884c732 duration=42.164202ms response_size=19854 status=200
level=info ts=2021-09-17T15:11:08.726815404Z caller=flush.go:157 msg="head block cut. enqueueing flush op" userid=single-tenant block=5ec589ad-0528-4b9c-84bd-13f99a994b5f
level=info ts=2021-09-17T15:11:17.624818984Z caller=flush.go:232 msg="completing block" userid=single-tenant blockID=5ec589ad-0528-4b9c-84bd-13f99a994b5f
panic: runtime error: index out of range [3] with length 0

goroutine 473 [running]:
github.com/google/flatbuffers/go.GetUint32(...)
	/home/zach/go/src/github.com/grafana/tempo/vendor/github.com/google/flatbuffers/go/encode.go:47
github.com/google/flatbuffers/go.GetUOffsetT(...)
	/home/zach/go/src/github.com/grafana/tempo/vendor/github.com/google/flatbuffers/go/encode.go:121
github.com/grafana/tempo/pkg/tempofb.GetRootAsSearchEntry(...)
	/home/zach/go/src/github.com/grafana/tempo/pkg/tempofb/SearchEntry.go:14
github.com/grafana/tempo/pkg/tempofb.SearchEntryFromBytes(...)
	/home/zach/go/src/github.com/grafana/tempo/pkg/tempofb/searchdata_util.go:257
github.com/grafana/tempo/tempodb/search.(*DataCombiner).Combine(0xc00257b230, {0x28, 0x266f400}, {0xc00257b260, 0x2, 0x185d9df})
	/home/zach/go/src/github.com/grafana/tempo/tempodb/search/data_combiner.go:28 +0x3a6
github.com/grafana/tempo/tempodb/encoding.(*dedupingIterator).Next(0xc0022bc660, {0x26b7098, 0xc000052038})
	/home/zach/go/src/github.com/grafana/tempo/tempodb/encoding/iterator_deduping.go:61 +0x237
github.com/grafana/tempo/tempodb/search.NewBackendSearchBlock(0xc0004fef60, 0xc00013c4d0, {0x5e, 0xc5, 0x89, 0xad, 0x5, 0x28, 0x4b, 0x9c, ...}, ...)
	/home/zach/go/src/github.com/grafana/tempo/tempodb/search/backend_search_block.go:64 +0x2f1
github.com/grafana/tempo/modules/ingester.(*instance).CompleteBlock(0xc0018b4480, {0x5e, 0xc5, 0x89, 0xad, 0x5, 0x28, 0x4b, 0x9c, 0x84, ...})
	/home/zach/go/src/github.com/grafana/tempo/modules/ingester/instance.go:272 +0x269
github.com/grafana/tempo/modules/ingester.(*Ingester).handleComplete(0xc0004c2c00, 0xc0017f7540)
	/home/zach/go/src/github.com/grafana/tempo/modules/ingester/flush.go:238 +0x25c
github.com/grafana/tempo/modules/ingester.(*Ingester).flushLoop(0xc0004c2c00, 0x1)
	/home/zach/go/src/github.com/grafana/tempo/modules/ingester/flush.go:195 +0xc7
created by github.com/grafana/tempo/modules/ingester.New
	/home/zach/go/src/github.com/grafana/tempo/modules/ingester/ingester.go:78 +0x1e9
```

**To Reproduce**
1. Start Tempo `3108978d` configured with memberlist and s3 backend pointed to minio
2. Start Vulture to send and query traces
3. Wait for completing block to happen

**Expected behavior**
Not panic.

**Environment:**
 - Infrastructure: laptop
 - Deployment tool: docker-compose

**Additional Context**

### PR DESCRIPTION
**Pull request by annanay25**
**What this PR does**:
Fixes an issue with WAL dedupe (SearchDataCombiner) when search is **disabled**. This happens because we still create search WAL files on the ingester with empty entries.

**Which issue(s) this PR fixes**:
Fixes #967 

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Comment by joe-elliott** [comment]
> This happens because we still create search WAL files on the ingester with empty entries.

I'm fine with this fix, but should we also not write an empty entry? Doesn't that mean we're incurring some write penalties even with search disabled?

**Comment by annanay25** [comment]
> I'm fine with this fix, but should we also not write an empty entry? Doesn't that mean we're incurring some write penalties even with search disabled?

So we are basically writing zero length objects to the search data file, which I don't think is costly. The solution to this is to have 

```
if i.searchEnabled {
  // bail
}
```
sprinkled all over the ingester code (CutCompleteTraces, CompleteBlock, Flush, ... etc).

Not sure if we want that, but open to suggestions.

File: tempodb/search/data_combiner.go [hunk 1]
```diff
@@ -25,6 +25,9 @@ func (*DataCombiner) Combine(_ string, searchData ...[]byte) ([]byte, bool) {
 	data := tempofb.SearchEntryMutable{}
 	kv := &tempofb.KeyValues{} // buffer
 	for _, sb := range searchData {
+		if len(sb) == 0 {
```
Comment (joe-elliott) [inline tempodb/search/data_combiner.go:28]: let's add a comment on why this guard code is required. lgtm.

**Review by joe-elliott — APPROVED** [review]
