### PR TITLE
TraceQL: Fix bug trying to optimize queries using only && and repeated attribute name

### LINKED ISSUE #1948: TraceQL: span scope not working with ranges
`{ span.http.status_code > 200 && span.http.status_code < 300 }` returns an empty resultset:

image

`{ .http.status_code > 200 && .http.status_code < 300 }` returns hits:

image

`{ span.http.status_code > 200 }` returns hits:

image

### PR DESCRIPTION
**Pull request by mdisibio**
**What this PR does**:
Fixes an issue when trying to optimize some queries using only `&&` which turns into the `AllConditions=true` storage layer hint, and including repeated attribute names.

**Which issue(s) this PR fixes**:
Fixes #1948 

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: pkg/traceql/storage.go [hunk 1]
```diff
@@ -61,26 +61,30 @@ type SpansetFetcher interface {
...
 	if err != nil {
-		return cond, err
+		return FetchSpansRequest{}, err
 	}
-	req := &FetchSpansRequest{}
-	ast.Pipeline.extractConditions(req)
-	return req.Conditions, nil
+
+	req := FetchSpansRequest{
+		AllConditions: true,
```
Comment (mapno) [inline pkg/traceql/storage.go:83]: I would add TODO here to remove when we support more types of queries.

**Review by mapno — APPROVED** [review]
