### PR TITLE
GCS error handling, example, and documentation

### LINKED ISSUE #379: compactor without GCS permissions fail silently
**Describe the bug**
If the compactor does not have access to the GCS bucket to read blocks it will silently fail without any logs that indicates that it failed reading from GCS. It is completely silent after:

```
level=info ts=2020-11-27T14:45:38.226122896Z caller=compactor.go:97 msg="enabling compaction"
level=info ts=2020-11-27T14:45:38.226173262Z caller=tempodb.go:349 msg="compaction and retention enabled."
```

**To Reproduce**
1. Use GCS backend with a private bucket
2. Deploy Tempo in a GKE cluster, set serviceAccountName for ingester and querier, but NOT for compactor
3. Send traces and wait for compactor to begin compacting

**Expected behavior**
Compactor should log an error stating that it cannot read from GCS due to lack of permissions.

**Environment:**
 - Kubernetes on GKE
 - jsonnet (we use Kustomize to patch)
- Tempo v0.3.0

**Additional Context**
The clue I got was from port-forward to 3100 on the compactor and scrolling through `/metrics`, eventually I saw this:

```
tempodb_gcs_request_duration_seconds_bucket{operation="GET",status_code="403",le="5.12"} 1
```

which led me to realize we had not set serviceAccountName for the compactor deployment

### PR DESCRIPTION
**Pull request by mdisibio**
**What this PR does**:
This PR addresses the silent errors encountered here: #379   The root cause was the consumption of the iterator in getting tenant and block list for GCS backend.  An error state with permissions could cause the loop to run infinitely and polling the blocklist would never complete.  This behavior is cautioned about here:  https://github.com/googleapis/google-cloud-go/blob/master/storage/bucket.go#L1183

This PR includes many updates, which will be explained here:

- Added an example compose to exercise the GCS backend using https://github.com/fsouza/fake-gcs-server
  - This requires adding a new gcs backend option `endpoint:string` to redirect api traffic.
  - This requires adding a new gcs backend option `insecure:bool` to disable authentication for the api using `option.WithoutAuthentication()`, which allows the storage client to run without error.
  - This requires an update to the GCS storage api client due to a header parsing bug here:  https://github.com/googleapis/google-cloud-go/commit/b580ccd2f35fa1c00b5cb0f521f073b5e63813d7#diff-e553a431afedc9d7ba6cb6997862fcf5f951aa3c28b552ad58537ebe797825dc  It seems not to be a problem for real GCS, but is required to use gcs-fake-server.
- gcs-fake-server can run in http mode and the storage client can theoretically do that as well, however in practice it does not work (details below). Therefore the gcs-fake-server is running in https mode.
  - This requires adding a new gcs backend option to disable TLS certificate checks due to self-signed cert.
  - The storage client checks for the presence of `STORAGE_EMULATOR_HOST` environment variable and when present configures the api to speak to the host using http.   However the storage client then loses the api prefix configured in the endpoint ("/storage/v1/") upon the first file write, breaking subsequent api calls.  See code here:  https://github.com/googleapis/google-cloud-go/blob/master/storage/writer.go#L129
- GCS backend was updated to check for bucket existence on startup. This helps to fail fast if there is a problem with permissions or infrastructure. Previously it wouldn't detect the error until the first block was written, or block list was polled.
- Added new GCS configuration documentation page, including the new options.

Other implementation notes:
- gcs/instrumentation.go which provides gcs request metrics, which simplified to only wrap a given RoundTripper, and the creation of the transport was moved gcs.go
- GCS backend creation:  updated for changes needed to disable tls cert checks, override endpoint, check bucket existence.
- Disabling tls checks requires making a clone of `http.DefaultTransport` which is then edited
- Some other error handling was tightened up:
  - Check error on writer.Close
  - errors.Wrap other errors for better troubleshooting

**Which issue(s) this PR fixes**:
Fixes #379

**Checklist**
- [ ] Tests updated
- [x] Documentation added
- [ ] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: tempodb/backend/gcs/gcs.go [hunk 1]
```diff
@@ -30,18 +35,48 @@ type readerWriter struct {
...
+	client, err := storage.NewClient(ctx, storageClientOptions...)
 	if err != nil {
-		return nil, nil, nil, err
+		return nil, nil, nil, errors.Wrap(err, "creating storage client")
 	}
 
 	bucket := client.Bucket(cfg.BucketName)
 
+	// Create bucket if needed.
+	if _, err = bucket.Attrs(ctx); err != nil {
```
Comment (joe-elliott) [inline tempodb/backend/gcs/gcs.go:70]: I'm wondering if this will fail in some installs b/c it requires additional permissions that Tempo is not yet using.

File: tempodb/backend/gcs/gcs.go [hunk 2]
```diff
@@ -67,12 +102,16 @@ func (rw *readerWriter) Write(ctx context.Context, meta *encoding.BlockMeta, bBl
 	defer src.Close()
 
 	w := rw.writer(ctx, util.ObjectFileName(blockID, tenantID))
-	defer w.Close()
 	_, err = io.Copy(w, src)
```
Comment (joe-elliott) [inline tempodb/backend/gcs/gcs.go:105]: if `io.Copy()` fails we never close the writer.  I guess you dropped the defer to catch the close error?  And maybe to force flush?

File: tempodb/backend/gcs/gcs.go [hunk 3]
```diff
@@ -242,20 +279,19 @@ func (rw *readerWriter) Shutdown() {
...
 	w := rw.writer(ctx, name)
-	defer w.Close()
 
 	_, err := w.Write(b)
 	if err != nil {
 		return err
 	}
 
-	return nil
+	err = w.Close()
```
Comment (joe-elliott) [inline tempodb/backend/gcs/gcs.go:288]: same questions as above re: defer.

**Review by joe-elliott — CHANGES_REQUESTED** [review]
Looks like you have to run `make vendor-check` and then I had a few questions.  Otherwise looks good.

File: tempodb/backend/gcs/gcs.go (hunk 1 above)
Comment (mdisibio) [reply tempodb/backend/gcs/gcs.go:70]: Reading the attrs requests `GET /storage/v1/b/<bucket>`, which needs `storage.buckets.get` permission here: https://cloud.google.com/storage/docs/access-control/iam-json   Agree this would be a new permission (doesn't look like it is required to read/write objects).   

This originally started as just an existence check in backend creation in order to fail faster, if there is a problem.  Previously, since the bucket is just a virtual handle, it wouldn't discover a problem until the first block list polling or block written. This change also has the benefit of making the issue a critical startup error, instead of a runtime error.

The bucket creation makes the gcs example easier.  Generally I am in favor of removing all bucket creation logic from tempo, since I think most users will have strong preferences/requirements on the creation of buckets (security/auditing/configuration/etc).   This standpoint applies to S3 as well.

File: tempodb/backend/gcs/gcs.go (hunk 2 above)
Comment (mdisibio) [reply tempodb/backend/gcs/gcs.go:105]: That's correct.  Thoughts on best approach to this?

File: tempodb/backend/gcs/gcs.go (hunk 3 above)
Comment (mdisibio) [reply tempodb/backend/gcs/gcs.go:290]: Updated to close writer on other error.

File: tempodb/backend/gcs/gcs.go (hunk 2 above)
Comment (mdisibio) [reply tempodb/backend/gcs/gcs.go:105]: Updated to close writer on other error.

File: docs/tempo/website/configuration/gcs.md [hunk 4]
```diff
@@ -0,0 +1,20 @@
+---
+title: Google Cloud Storage (GCS)
+---
+
+# GCS Configuration
+GCS backend is configured in the storage block.  Tempo requires a dedicated bucket since it maintains a top-level object structure and does not support a custom prefix to nest within a shared bucket.
```
Comment (achatterjee-grafana) [inline docs/tempo/website/configuration/gcs.md:6]:
```suggestion
GCS backend is configured in the storage block. Tempo requires a dedicated bucket since it maintains a top-level object structure and does not support a custom prefix to nest within a shared bucket.
```

File: docs/tempo/website/configuration/gcs.md [hunk 5]
```diff
@@ -0,0 +1,20 @@
+---
+title: Google Cloud Storage (GCS)
+---
+
+# GCS Configuration
```
Comment (achatterjee-grafana) [inline docs/tempo/website/configuration/gcs.md:5]:
```suggestion
# Google Cloud Storage (GCS) configuration
```

File: docs/tempo/website/configuration/gcs.md [hunk 6]
```diff
@@ -0,0 +1,20 @@
...
+        backend: gcs                                              # store traces in gcs
+        s3:
+            bucket_name: tempo                                    # store traces in this bucket
+            chunk_buffer_size: 10485760                           # optional. buffer size for reads. default = 10MiB
+            endpoint: https://storage.googleapis.com/storage/v1/  # optional. api endpoint override
+            insecure: false                                       # optional. Set to true to disable authentication 
+                                                                  #   and certificate checks.
+            project_id: project                                   # optional if bucket already exists. Project ID
+                                                                  #   to use when creating bucket on first run.
+```
```
Comment (achatterjee-grafana) [inline docs/tempo/website/configuration/gcs.md:20]:
```suggestion
    trace:
        backend: gcs                                              # Store traces in gcs.
        s3:
            bucket_name: tempo                                    # Store traces in this bucket.
            chunk_buffer_size: 10485760                           # Optional, buffer size for reads. Default = 10MiB
            endpoint: https://storage.googleapis.com/storage/v1/  # Optional, API endpoint override.
            insecure: false                                       # Optional, set to true to disable authentication
                                                                  #   and certificate checks.
            project_id: project                                   # Optional, if bucket already exists. Project ID
                                                                  #   to use when creating a bucket on the first run.
```
```

File: example/docker-compose/etc/tempo-gcs-fake.yaml [hunk 7]
```diff
@@ -0,0 +1,48 @@
+auth_enabled: false
+
+server:
+  http_listen_port: 3100
+
+distributor:
+  receivers:                           # this configuration will listen on all ports and protocols that tempo is capable of.
```
Comment (achatterjee-grafana) [inline example/docker-compose/etc/tempo-gcs-fake.yaml:7]:
```suggestion
  receivers:                           # This configuration will listen on all ports and protocols that tempo is capable of listening to.
```

File: example/docker-compose/etc/tempo-gcs-fake.yaml [hunk 8]
```diff
@@ -0,0 +1,48 @@
...
+    jaeger:                            # the receives all come from the OpenTelemetry collector.  more configuration information can
+      protocols:                       # be found there: https://github.com/open-telemetry/opentelemetry-collector/tree/master/receiver
+        thrift_http:                   #
+        grpc:                          # for a production deployment you should only enable the receivers you need!
+        thrift_binary:
```
Comment (achatterjee-grafana) [inline example/docker-compose/etc/tempo-gcs-fake.yaml:12]:
```suggestion
    jaeger:                            # Receives all traces? coming from the OpenTelemetry collector. More configuration information can
      protocols:                       # be found here: https://github.com/open-telemetry/opentelemetry-collector/tree/master/receiver
        thrift_http:                   #
        grpc:                          # For a production deployment you should only enable the receivers you need!
        thrift_binary:
```

File: example/docker-compose/etc/tempo-gcs-fake.yaml [hunk 9]
```diff
@@ -0,0 +1,48 @@
...
+    opencensus:
+
+ingester:
+  trace_idle_period: 10s               # the length of time after a trace has not received spans to consider it complete and flush it
+  traces_per_block: 100                # cut the head block when it his this number of traces or ...
+  max_block_duration: 5m               #   this much time passes
+
+compactor:
+  compaction:
+    compaction_window: 1h              # blocks in this time window will be compacted together
```
Comment (achatterjee-grafana) [inline example/docker-compose/etc/tempo-gcs-fake.yaml:28]:
```suggestion
    compaction_window: 1h              # Blocks in this time window will be compacted together.
```

File: example/docker-compose/etc/tempo-gcs-fake.yaml [hunk 10]
```diff
@@ -0,0 +1,48 @@
...
+    max_compaction_objects: 1000000    # maximum size of compacted blocks
```
Comment (achatterjee-grafana) [inline example/docker-compose/etc/tempo-gcs-fake.yaml:29]:
```suggestion
    max_compaction_objects: 1000000    # Maximum size of the compacted blocks.
```

File: example/docker-compose/etc/tempo-gcs-fake.yaml [hunk 11]
```diff
@@ -0,0 +1,48 @@
...
+    otlp:
+      protocols:
+        http:
+        grpc:
+    opencensus:
+
+ingester:
+  trace_idle_period: 10s               # the length of time after a trace has not received spans to consider it complete and flush it
+  traces_per_block: 100                # cut the head block when it his this number of traces or ...
+  max_block_duration: 5m               #   this much time passes
```
Comment (achatterjee-grafana) [inline example/docker-compose/etc/tempo-gcs-fake.yaml:24]:
```suggestion
  trace_idle_period: 10s               # The length of time after a trace has not received spans to consider it complete. and flush it
  traces_per_block: 100                # Cut the head block when it has the specified number of traces or ...
  max_block_duration: 5m               #   this much of time has elapsed.
```

File: example/docker-compose/etc/tempo-gcs-fake.yaml [hunk 12]
```diff
@@ -0,0 +1,48 @@
...
+  compaction:
+    compaction_window: 1h              # blocks in this time window will be compacted together
+    max_compaction_objects: 1000000    # maximum size of compacted blocks
+    block_retention: 1h
+    compacted_block_retention: 10m
+    flush_size_bytes: 5242880
+
+storage:
+  trace:
+    backend: gcs                       # backend configuration to use
```
Comment (achatterjee-grafana) [inline example/docker-compose/etc/tempo-gcs-fake.yaml:36]:
```suggestion
    backend: gcs                       # The backend configuration to use.
```

File: example/docker-compose/etc/tempo-gcs-fake.yaml [hunk 13]
```diff
@@ -0,0 +1,48 @@
...
+    wal:
+      path: /tmp/tempo/wal             # where to store the the wal locally
```
Comment (achatterjee-grafana) [inline example/docker-compose/etc/tempo-gcs-fake.yaml:38]:
```suggestion
      path: /tmp/tempo/wal             # Path to store the wal locally.
```

File: example/docker-compose/etc/tempo-gcs-fake.yaml [hunk 14]
```diff
@@ -0,0 +1,48 @@
...
+      bloom_filter_false_positive: .05 # bloom filter false positive rate.  lower values create larger filters but fewer false positives
+      index_downsample: 10             # number of traces per index record
```
Comment (achatterjee-grafana) [inline example/docker-compose/etc/tempo-gcs-fake.yaml:40]:
```suggestion
      index_downsample: 10             # Number of traces per index record.
```

File: example/docker-compose/etc/tempo-gcs-fake.yaml [hunk 15]
```diff
@@ -0,0 +1,48 @@
...
+    gcs:
+      bucket_name: tempo
+      endpoint: https://gcs:4443/storage/v1/
+      insecure: true
+      project_id: test
+    pool:
+      max_workers: 100                 # the worker pool mainly drives querying, but is also used for polling the blocklist
```
Comment (achatterjee-grafana) [inline example/docker-compose/etc/tempo-gcs-fake.yaml:47]:
```suggestion
      max_workers: 100                 # The worker pool mainly drives querying but it is also used for polling the blocklist.
```

File: example/docker-compose/etc/tempo-gcs-fake.yaml (hunk 14 above)
Comment (achatterjee-grafana) [inline example/docker-compose/etc/tempo-gcs-fake.yaml:40]:
```suggestion
      bloom_filter_false_positive: .05 # The bloom filter false positive rate. Lower values create larger filters but fewer false positives.
      index_downsample: 10             # Number of traces per index record.
```

**Review by achatterjee-grafana — CHANGES_REQUESTED** [review]
Added few copy-edit suggestions.

**Comment by joe-elliott** [comment]
For the yaml comments I personally prefer lower case and brevity to grammatically correct sentences.  my .02

File: tempodb/backend/gcs/gcs.go (hunk 1 above)
Comment (mdisibio) [reply tempodb/backend/gcs/gcs.go:70]: As discussed, removed the bucket creation but retained the existence check and fast failing.

**Review by joe-elliott — APPROVED** [review]
