### PR TITLE
enhancement: supported deduping spans within block builder

### LINKED ISSUE #6516: Need to deduplicate spans in the block builder
**Describe the bug**
Due to network, software, or config issues, it's possible for Tempo to receive the same data multiple times.  This is handled by deduplication in several places including search, trace by ID lookup, and compaction.  However a large gap is traceql metrics queries, which do not dedupe and expect storage to be clean.

We can add dedupe to block-builder and improve things.  

I would add it in [func (i *liveTracesIter) iter(ctx context.Context)](https://github.com/grafana/tempo/blob/main/modules/blockbuilder/live_traces_iter.go#L113)  That is the point at which we unmarshal the proto and reconstruct the full trace, before writing to the block.

Let's also add a metric similar to the compactor for [deduped spans](https://github.com/grafana/tempo/blob/main/tempodb/compactor.go#L66), which would be good for troubleshooting and monitoring the effectiveness of this dedupe over time.

### PR DESCRIPTION
**Pull request by zhxiaogg**
**What this PR does**:
- Block builder: deduplicate spans within traces during block creation and track removed duplicates via `tempo_block_builder_spans_deduped_total` metric

**Which issue(s) this PR fixes**:
Fixes #6516

**Test**
- can verify the metrics are generated and showing in prometheus ui when testing with singlebinary example.

**Checklist**
- [x] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: modules/blockbuilder/live_traces_iter.go [hunk 1]
```diff
@@ -151,8 +156,40 @@ func (i *liveTracesIter) MinMaxTimestamps() (uint64, uint64) {
...
+// dedupeTrace removes duplicate spans in-place from tr, deduplicating by span ID and kind.
+// Returns the number of removed duplicate spans.
+func dedupeTrace(tr *tempopb.Trace) uint32 {
+	seen := make(map[uint64]struct{})
+	var deduped uint32
+	for _, rs := range tr.ResourceSpans {
+		for _, ss := range rs.ScopeSpans {
+			unique := ss.Spans[:0]
+			for _, s := range ss.Spans {
+				token := util.SpanIDAndKindToToken(s.SpanId, int(s.Kind))
```
Comment (javiermolinar) [inline modules/blockbuilder/live_traces_iter.go]: I wonder if we should use this hashing algorithm instead:

https://github.com/grafana/tempo/blob/2ad734b16785d8be4a52c319265a2e523a1c05c8/pkg/model/trace/combine.go#L27

It seems more correct, with less chances of collisions

File: modules/blockbuilder/live_traces_iter.go [hunk 2]
```diff
@@ -151,8 +156,40 @@ func (i *liveTracesIter) MinMaxTimestamps() (uint64, uint64) {
...
 }
 
+// dedupeTrace removes duplicate spans in-place from tr, deduplicating by span ID and kind.
+// Returns the number of removed duplicate spans.
+func dedupeTrace(tr *tempopb.Trace) uint32 {
+	seen := make(map[uint64]struct{})
+	var deduped uint32
+	for _, rs := range tr.ResourceSpans {
+		for _, ss := range rs.ScopeSpans {
+			unique := ss.Spans[:0]
```
Comment (stoewer) [inline modules/blockbuilder/live_traces_iter.go]: Nice in-place dedup 👍

File: modules/blockbuilder/live_traces_iter.go [hunk 3]
```diff
@@ -151,8 +156,40 @@ func (i *liveTracesIter) MinMaxTimestamps() (uint64, uint64) {
...
+}
+
 func (i *liveTracesIter) Close() {
 	i.cancel()
 }
 
+// dedupeTrace removes duplicate spans in-place from tr, deduplicating by span ID and kind.
+// Returns the number of removed duplicate spans.
+func dedupeTrace(tr *tempopb.Trace) uint32 {
+	seen := make(map[uint64]struct{})
```
Comment (stoewer) [inline modules/blockbuilder/live_traces_iter.go]: There is an opportunity here to save lots of smaller heap allocations:
* Initialize `seen` with a reasonable start size in to avoid allocations and rehashing when the map grows
* Reuse the `seen` in multiple deduplications (and use `clear(seen)` before reuse)

File: modules/blockbuilder/live_traces_iter.go [hunk 4]
```diff
@@ -109,6 +111,9 @@ func (i *liveTracesIter) iter(ctx context.Context) {
 				}
 			}
 
+			// Deduplicate spans within the trace
+			i.dedupedSpans += dedupeTrace(tr)
```
Comment (stoewer) [inline modules/blockbuilder/live_traces_iter.go]: Each trace is traversed twice: one time in `dedupeTrace()` and another time in L118 to update timestamp bounds. Maybe those can be combined

File: modules/blockbuilder/live_traces_iter.go [hunk 5]
```diff
@@ -151,8 +156,40 @@ func (i *liveTracesIter) MinMaxTimestamps() (uint64, uint64) {
 	return i.start, i.end
 }
 
+// DedupedSpans returns the total number of duplicate spans that were removed
+// across all traces. The iterator must be exhausted before this can be accessed.
```
Comment (stoewer) [inline modules/blockbuilder/live_traces_iter.go]: > The iterator must be exhausted before this can be accessed

Just for the sake of being a bit more defensive, what do you think about enforcing this by returning an error when `liveTracesIter.DedupedSpans()` is called before it's exhausted?

File: modules/blockbuilder/live_traces_iter.go (hunk 1 above)
Comment (zhxiaogg) [reply modules/blockbuilder/live_traces_iter.go]: thanks, changed to use the alternative one you suggested!

File: modules/blockbuilder/live_traces_iter.go (hunk 3 above)
Comment (zhxiaogg) [reply modules/blockbuilder/live_traces_iter.go]: thanks, all changed including the following comments.
