### PR TITLE
fix nil pointer error on trace by id path

### LINKED ISSUE #1440: Trace query causes runtime error: invalid memory address or nil pointer dereference
**Describe the bug**
Trying to query a specific `TraceId` in Grafana, getting "Query data error". Many traces can be viewed, some return this error. Not really sure what the reason is. Logs from Tempo after the failed query in Grafana:

```
2022-05-23 18:33:45.269731 I | http: panic serving 10.9.2.8:50694: runtime error: invalid memory address or nil pointer dereference
goroutine 4086 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1802 +0xb9
panic({0x1ae7780, 0x32682c0})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
github.com/opentracing-contrib/go-stdlib/nethttp.MiddlewareFunc.func5.1()
	/drone/src/vendor/github.com/opentracing-contrib/go-stdlib/nethttp/server.go:150 +0x139
panic({0x1ae7780, 0x32682c0})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/grafana/tempo/modules/frontend.newTraceByIDMiddleware.func1.1(0xc04e4fbe00)
	/drone/src/modules/frontend/frontend.go:169 +0x8f0
github.com/grafana/tempo/modules/frontend.RoundTripperFunc.RoundTrip(0x1dce37d, 0x1dc1f75)
	/drone/src/modules/frontend/middleware.go:13 +0x1f
github.com/grafana/tempo/modules/frontend.(*handler).ServeHTTP(0xc040e14de0, {0x22597b8, 0xc00012e930}, 0xc04e4fbe00)
```

**To Reproduce**
1. Tempo installed via Helm (`tempo` chart, version 0.15.0) in Kubernetes
2. `values.yaml`:

```
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "3100"

tempo:
  resources:
    requests:
      cpu: 500m
      memory: 3Gi
    limits:
      cpu: 2000m
      memory: 6Gi

  storage:
    trace:
      backend: azure
      block:
        bloom_filter_false_positive: .05
        index_downsample_bytes: 1000
        encoding: zstd
      wal:
        path: /tmp/tempo/wal
        encoding: snappy
      azure:
        container-name: tempo
        storage-account-name: <will_be_replaced_by_secret>
        storage-account-key: <will_be_replaced_by_secret>
      pool:
        max_workers: 100
        queue_depth: 10000

  overrides:
    max_bytes_per_trace: 50000000

  ingester:
    trace_idle_period: 10s
    flush_check_period: 5s
    max_block_bytes: 1_000_000
    max_block_duration: 5m

  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
    jaeger: null
    opencensus: null
```

**Expected behavior**
That I can view the Trace in Grafana

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: Helm

I'd be happy to provide more information if needed!

### PR DESCRIPTION
**Pull request by joe-elliott**
**What this PR does**:
- Moves the reference to `resp` to inside of the block where resp != nil
- Adds additional guard code against `resp.Header` being nil.

**Which issue(s) this PR fixes**:
Fixes #1440 

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by zalegrala — APPROVED** [review]

File: modules/frontend/frontend.go [hunk 1]
```diff
@@ -161,14 +161,16 @@ func newTraceByIDMiddleware(cfg Config, logger log.Logger) Middleware {
 					}
 					resp.Body = io.NopCloser(bytes.NewReader(traceBuffer))
 				}
+
+				if resp.Header != nil {
```
Comment (mdisibio) [inline modules/frontend/frontend.go:165]: The containing if statement also checks for http status OK.  Does the header need to be set for errors as well?  I'm honestly unsure.

Comment (joe-elliott) [reply modules/frontend/frontend.go:165]: I actually think this is better. Our errors tend to be just text so we probably shouldn't be setting the `Content-Type` header.
