### PR TITLE
 Increase Prometheus not found metric on tempo-vulture

### LINKED ISSUE #286: tempo-vulture doesn't correctly metric 404s
**Describe the bug**
Even when the querier returns a 404 the tempo-vulture does not metric it correctly.  Instead it logs:

```
E1029 17:32:44.343430       1 main.go:115] tempo url http://querier:3100/api/traces/3359040636e8a98b
E1029 17:32:44.560477       1 main.go:91] error querying Tempo error decoding trace json, err: invalid character 'U' looking for beginning of value, traceID: 3359040636e8a98b
```

### PR DESCRIPTION
**Pull request by dgzlopes**
**What this PR does**:
This PR adds some things:
- Return a `not found error` in case we don't find the traceID.
- Increase Prometheus not found metric on tempo-vulture.

I'm not a Go expert, but this approach seemed "reasonable" :smile:

**Which issue(s) this PR fixes**:
Fixes #286

**Checklist**
- [ ] Tests updated
- [ ] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

File: cmd/tempo-vulture/main.go [hunk 1]
```diff
@@ -115,6 +115,11 @@ func queryTempoAndAnalyze(baseURL string, backoff time.Duration, traceIDs []stri
 		glog.Error("tempo url ", baseURL+"/api/traces/"+id)
 		trace, err := util.QueryTrace(baseURL, id, tempoOrgID)
 		if err != nil {
+			if strings.Contains(err.Error(), "not found") {
```
Comment (joe-elliott) [inline cmd/tempo-vulture/main.go:118]: It would be preferred to define and export an error from the util package like:

```
var ErrTraceNotFound = errors.New("trace not found")
```

The calling code can then compare using simple equality instead of a `string.Contains` method

```
if err == util.ErrTraceNotFound {
}
```

**Review by joe-elliott — CHANGES_REQUESTED** [review]

File: cmd/tempo-vulture/main.go (hunk 1 above)
Comment (annanay25) [reply cmd/tempo-vulture/main.go:118]: +1

Comment (dgzlopes) [reply cmd/tempo-vulture/main.go:118]: Thanks for the review! Yep, that way it's cleaner. I'll update the PR :)

File: cmd/tempo-vulture/main.go [hunk 2]
```diff
@@ -115,6 +115,11 @@ func queryTempoAndAnalyze(baseURL string, backoff time.Duration, traceIDs []stri
 		glog.Error("tempo url ", baseURL+"/api/traces/"+id)
 		trace, err := util.QueryTrace(baseURL, id, tempoOrgID)
 		if err != nil {
+			if err == util.ErrTraceNotFound {
```
Comment (joe-elliott) [inline cmd/tempo-vulture/main.go:118]: one final nit.  let's reduce nesting here:
```
if err == util.ErrTraceNotFound {
   ...
}
if err != nil {
   ...
}
```

**Review by joe-elliott — APPROVED** [review]

**Comment by joe-elliott** [comment]
Thanks again!
