### PR TITLE
query-frontend/retry: properly handle grpc errors; lower default max_retries

### LINKED ISSUE #824: Query-frontend retries queries that timed out in querier
**Describe the bug**
After merging #814 I noticed the query-frontend is retrying request that timed out in the querier.

The good: after retrying the request, it usually succeeds quickly
The bad: if we keep retrying a query that timed out, the query might hang for up `max_retries * query_timeout` seconds (50s by default).

An example of such a trace:

Screenshot 2021-07-16 at 14 52 32

**To Reproduce**
1. Start Tempo (2ad27e7c or more recent)
2. Perform a query
3. If the querier times out, observe retries in the query-frontend

**Expected behavior**
I'm not sure to be honest. Some options:

- do not retry a query that timed out
- enforce a timeout in the query-frontend
- leave it as is (but a request that OOMs the querier could be sent 5 times this way)

### LINKED ISSUE #843: Query-frontend will occasionally panic when under sustained load
**Describe the bug**

Query-frontend will occasionally panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x47ad05]
goroutine 302 [running]:
errors.(*errorString).Error(0x0, 0x209c7e0, 0x0)
	/usr/local/go/src/errors/errors.go:68 +0x5
github.com/opentracing/opentracing-go/log.Field.Marshal(0x2485b37, 0xc, 0x9, 0x0, 0x0, 0x0, 0x209c7e0, 0x0, 0x2995038, 0xc06a0b00d8)
	/drone/src/vendor/github.com/opentracing/opentracing-go/log/field.go:231 +0x309
github.com/uber/jaeger-client-go.ConvertLogsToJaegerTags(0xc000a68780, 0x3, 0x3, 0xc06984e008, 0x39c7248, 0xc000cfbd78)
	/drone/src/vendor/github.com/uber/jaeger-client-go/jaeger_tag.go:31 +0x13f
github.com/uber/jaeger-client-go.buildLogs(0xc06975e480, 0x1, 0x1, 0x100, 0x39c7248, 0x0)
	/drone/src/vendor/github.com/uber/jaeger-client-go/jaeger_thrift_span.go:82 +0x145
github.com/uber/jaeger-client-go.BuildJaegerThrift(0xc0697586c0, 0x0)
	/drone/src/vendor/github.com/uber/jaeger-client-go/jaeger_thrift_span.go:43 +0x16c
github.com/uber/jaeger-client-go.(*udpSender).Append(0xc000ccad80, 0xc0697586c0, 0x0, 0x0, 0x2)
	/drone/src/vendor/github.com/uber/jaeger-client-go/transport_udp.go:129 +0x45
github.com/uber/jaeger-client-go.(*remoteReporter).processQueue(0xc000533f80)
	/drone/src/vendor/github.com/uber/jaeger-client-go/reporter.go:304 +0x1c2
created by github.com/uber/jaeger-client-go.NewRemoteReporter
	/drone/src/vendor/github.com/uber/jaeger-client-go/reporter.go:237 +0x1a5
```

We observed this while receiving a constant load of about 23 queries per second.

**To Reproduce**
1. Run Tempo
2. Send a ton of queries

**Expected behavior**
Tempo should not panic.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: jsonnet

**Additional Context**

### LINKED ISSUE #844: Retry tripperware will retry 429 errors wrapped in RPC errors
**Describe the bug**
I've spotted the retry tripperware retrying HTTP 429 errors (= too many requests).

Screenshot 2021-07-30 at 14 38 46

**To Reproduce**
1. Run Tempo
2. Perform queries
3. Wait untli the querier returns with an HTTP 4xx error (I guess?)

**Expected behavior**
We should not retry 4xx errors, these are caused by the caller. In fact, retrying a 429 error will make matters worse 😬 

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: jsonnet

**Additional Context**

### PR DESCRIPTION
**Pull request by kvrhdn**
**What this PR does**:
Improves the retry middleware in query-frontend:
- when err is a grpc error, extract http response and check status code (fixes #844)
- lower default retry to 2
- add a prometheus metric `query_frontend_retries`
- don't log errors (avoids #843)

**Which issue(s) this PR fixes**:
Closes #844
Closes #843
Supersedes #849
Closes #824

**Checklist**
- [x] Tests updated
- [x] Documentation added
- [x] `CHANGELOG.md` updated - the order of entries should be `[CHANGE]`, `[FEATURE]`, `[ENHANCEMENT]`, `[BUGFIX]`

### CODE REVIEW

**Review by achatterjee-grafana — APPROVED** [review]

File: modules/frontend/retry.go [hunk 1]
```diff
@@ -42,25 +50,23 @@ func (r retryWare) Do(req *http.Request) (*http.Response, error) {
...
+			return resp, err
 		}
 
-		span.LogFields(
-			ot_log.String("msg", "error processing request"),
-			ot_log.Int("status_code", statusCode),
-			ot_log.Error(err),
-			ot_log.Int("triesLeft", triesLeft),
-		)
+		span.LogFields(ot_log.String("msg", "error processing request. retrying"))
```
Comment (mdisibio) [inline modules/frontend/retry.go:70]: What is the thinking to remove the extra data from the span? It seems helpful.

File: modules/frontend/retry.go [hunk 2]
```diff
@@ -42,25 +50,23 @@ func (r retryWare) Do(req *http.Request) (*http.Response, error) {
...
 		if err == nil && resp.StatusCode/100 != 5 {
 			return resp, nil
 		}
 
-		statusCode := 0
-		if resp != nil {
-			statusCode = resp.StatusCode
+		// do not retry if GRPC error contains response that is not HTTP 5xx
+		httpResp, ok := httpgrpc.HTTPResponseFromError(err)
+		if ok && httpResp.Code/100 != 5 {
```
Comment (mdisibio) [inline modules/frontend/retry.go:60]: Researching on which http status codes are retry-able, it seems maybe we shouldn't retry 501 (Not Implemented), but should also retry 429 (Too Many Requests).  What do you think?

**Review by mdisibio — APPROVED** [review]
LGTM, left a few comments but not blocking. This solves the main issue of not retrying on 4xx.

File: modules/frontend/retry.go (hunk 1 above)
Comment (kvrhdn) [reply modules/frontend/retry.go:70]: I removed `ot_log.Error(err)` because this triggers https://github.com/grafana/tempo/issues/843
Agree it's valuable info, but for some reason calling `err.Error()` can cause panics 🙃 

I'll re-add the tries.

File: modules/frontend/retry.go (hunk 2 above)
Comment (kvrhdn) [reply modules/frontend/retry.go:60]: 429 is intended as a kind of rate-limiting I believe, if you get this you should send less requests. So I don't want to retry this to avoid piling on even more.

If we can ensure retries are sent to a different querier, I agree it would be good to retry this as well. #856

Comment (kvrhdn) [reply modules/frontend/retry.go:61]: I think it's fine to ignore 501 since this shouldn't happen within Tempo. If we hit an endpoint that is not enabled (for instance with search) Tempo returns 404 not found.

File: modules/frontend/retry.go (hunk 1 above)
Comment (kvrhdn) [reply modules/frontend/retry.go]: Found a safe way to log the error 🙃

File: modules/frontend/retry.go (hunk 2 above)
Comment (kvrhdn) [reply modules/frontend/retry.go]: Yeah grpc returns 429 errors: I've seen the queriers return 429 when Tempo was getting a lot of request.

Comment (mdisibio) [reply modules/frontend/retry.go]: Oh I just realized that retrying on 429 prompted this fix in #844.  Yep agree that might be good to explore later with better logic: a different querier or a backoff algorithm.
